// AirSkyHero hero list. To add a hero, copy one entry, change the fields, and keep the commas.
// id: short unique name used in links (airskyhero.com/#hero-<id>). role: Pilot, Cabin crew or Passenger.
// image fields are optional; only use freely licensed images (e.g. Wikimedia Commons) and keep the credit.
// aboard / survived are optional: leave them out where the count is not well established.
// featured: true puts a hero in the "Featured hero" spot at the top of the page.
// developing: true marks a recent event whose details may still change.
// news: optional coverage shown in the hero's story, newest first. type is "video" (YouTube link, plays in the page)
//   or "article". title, date (YYYY-MM-DD) and image (the article's preview picture) are optional. Every hero also gets "latest news" search links automatically.
// newsQuery: optional search words for those links (defaults to the hero's name and flight).
// slug: optional page address (airskyhero.com/<slug>/); defaults to the name, e.g. "smit-machchhar".
// After editing this file, run "npm run build" to update the hero pages, share images and sitemap.
const HEROES = [
  { id: "machchhar", name: "Smit Machchhar", role: "Pilot", country: "India", year: 2026,
    featured: true, developing: true,
    date: "30 September 2026", flight: "flydubai Flight 1073", aircraft: "Boeing 737 MAX 8", place: "Tabuk, Saudi Arabia",
    story: "Captain Smit Machchhar was flying flydubai Flight 1073 from Dubai to Tel Aviv when, according to initial reports, he was attacked in the cockpit by the first officer and the aircraft went into a rapid descent. Though seriously injured, he is reported to have opened the cockpit door, allowing passengers and crew to restrain the attacker. Off-duty pilots travelling on board took over and the Boeing 737 MAX 8 landed safely at Tabuk, Saudi Arabia, with all 174 passengers alive. The investigation is ongoing.",
    source: "https://en.wikipedia.org/wiki/Flydubai_Flight_1073",
    news: [
      { type: "video", title: "Captain Smit Machchhar's Wife Says, 'Very Delighted That PM Modi Spoke To Him'", outlet: "Moneycontrol", url: "https://www.youtube.com/watch?v=ry80jwnw2nA" },
      { type: "video", title: "UAE Crown Prince Sheikh Hamdan visits Captain Smit Machchhar in hospital", outlet: "DD India", url: "https://www.youtube.com/watch?v=xEnbfqlHN3g" },
      { type: "article", title: "Flydubai pilot Smit Machchhar: I couldn't let everybody else die", outlet: "CNN", date: "2026-10-02", url: "https://www.cnn.com/2026/10/02/middleeast/i-couldnt-let-everybody-else-die-says-hero-flydubai-pilot-smit-machchhar", image: "https://media.cnn.com/api/v1/images/stellar/videothumbnails/27947023-11227013-generated-thumbnail.jpg?c=16x9&q=w_800,c_fill" },
      { type: "article", title: "'Hero To World': Netanyahu Invites Smit Machchhar To Independence Day Event", outlet: "NDTV", url: "https://www.ndtv.com/world-news/hero-to-entire-world-netanyahu-invites-flydubai-hero-to-israel-independence-day-event-12135282", image: "https://c.ndtvimg.com/2026-10/8g4svmcc_netanyahu-afp_625x300_01_October_26.jpeg?im=FeatureCrop,algorithm=dnn,width=800,height=450" },
      { type: "article", title: "Mankind Pharma honours Captain Smit Machchhar with Rs 1 crore for 'extraordinary courage'", outlet: "ThePrint", date: "2026-10-02", url: "https://theprint.in/feature/mankind-pharma-captain-smit-machchhar-1-crore-extraordinary-courage/3060475/", image: "https://staticprintenglish.theprint.in/wp-content/uploads/2026/10/Untitled-design-21.jpg" },
      { type: "article", title: "Indian pilot Smit Machchhar recalls battling for lives in cockpit", outlet: "Gulf News", url: "https://gulfnews.com/business/aviation/flydubai-pilot-reveals-what-happened-in-cockpit-i-couldnt-let-everybody-else-die-1.500695904", image: "https://media.assettype.com/gulfnews%2F2026-10-02%2Fzhq4h7ai%2FHTm4pztWQAAXw-m.jpg?w=800&ar=16%3A9&auto=format%2Ccompress&mode=crop" },
      { type: "article", title: "Capt Smit Machchhar's wife recounts horrifying moments as she heard of flydubai cockpit attack", outlet: "The Tribune", url: "https://www.tribuneindia.com/news/world/was-devastated-didnt-have-mental-capacity-to-react-capt-smit-machchhars-wife-recounts-horrifying-moments-as-she-heard-of-flydubai-cockpit-attack/amp/", image: "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYWRhMjQ2OTQwLWJlNGItMTFmMS05N2QyLTcxMzIwNTZiZTJjZS5qcGc=" },
      { type: "article", title: "'India and Israel should be very proud': US hails Indian pilot, Israeli passengers", outlet: "The Tribune", url: "https://www.tribuneindia.com/news/india/india-and-israel-should-be-very-proud-us-hails-indian-pilot-israeli-passengers-for-averting-flydubai-terror-attack/", image: "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTg4OGMyZDYwLWJmNDYtMTFmMS05N2QyLTcxMzIwNTZiZTJjZS5qcGc=" },
      { type: "article", title: "UAE Deputy PM meets Smit Machchhar at Abu Dhabi hospital, says country's leadership praises his courage", outlet: "Daily Jagran", url: "https://www.thedailyjagran.com/world/news/uae-deputy-pm-meets-smit-machchhar-at-abu-dhabi-hospital-says-countrys-leadership-praises-his-courage-10331440", image: "https://images.thedailyjagran.com/images/2026/10/03/template/image/smit-machchhar-1791031015859.webp" },
      { type: "article", title: "Captain Smit Machchhar 'in good health and recovering well', says India's embassy in the UAE", outlet: "ETV Bharat", url: "https://www.etvbharat.com/en/international/live-blog--flydubai-incident-live-updates-captain-smit-machchhar-indian-pilot-saves-lives-israel-saudi-arabia-uae-benjamin-netanyahu-enn26100102127", image: "https://imgs.etvbharat.com/etvbharat/prod-images/01-10-2026/1200-675-27761616-948-27761616-1790834538309.jpg" },
      { type: "article", title: "Flydubai Flight FZ1073 heroes: who are the 5 people who helped avert a mid-air disaster?", outlet: "Sunday Guardian", url: "https://sundayguardianlive.com/world/flydubai-flight-fz1073-heroes-who-are-the-5-people-who-helped-avert-a-mid-air-disaster-indian-pilot-plumber-banker-businessman-and-dentist-296430/", image: "https://sundayguardianlive.com/wp-content/uploads/2026/10/flydubai-flight-fz1073-heroes-who-helped-avert-a-mid-air-disaster-on-the-dubai-tel-aviv-flight.png" },
      { type: "article", title: "Who is Smit Machchhar? Flydubai pilot stabbed identified by Israel PM Netanyahu", outlet: "Newsweek", url: "https://www.newsweek.com/who-is-capt-smit-machchhar-flydubai-pilot-flight-fz1073-12509226", image: "https://assets.newsweek.com/wp-content/uploads/2026/09/newsweek-main-crop.jpg?w=800&crop=1" },
      { type: "article", title: "Pilot suspected of Flydubai attack transferred to UAE as investigation unfolds", outlet: "CNN", date: "2026-10-01", url: "https://www.cnn.com/2026/10/01/world/live-news/flydubai-flight-israel-pilot-passengers-intl", image: "https://media.cnn.com/api/v1/images/stellar/prod/2026-09-30t152357z-2093004972-rc2rtnaksbz0-rtrmadp-3-israel-gulf-flight-passengers-tabuk.JPG?c=16x9&q=w_800,c_fill" },
      { type: "article", title: "Flydubai co-pilot ‘assaulted’ captain before landing: initial Saudi probe", outlet: "Al Jazeera", date: "2026-10-01", url: "https://www.aljazeera.com/news/2026/10/1/flydubai-co-pilot-assaulted-captain-before-landing-initial-saudi-probe", image: "https://www.aljazeera.com/wp-content/uploads/2026/10/afp_6abebf3c75ec-1790885692.jpg?resize=800%2C450" },
      { type: "article", title: "Passengers and crew foil co-pilot's apparent attempt to crash FlyDubai flight to Israel", outlet: "CNBC", date: "2026-10-01", url: "https://www.cnbc.com/2026/10/01/dubai-israel-flight-pilot-crash-indian.html", image: "https://image.cnbcfm.com/api/v1/image/108370773-1790813698247-gettyimages-2297373318-_erm5466.jpeg?v=1790813718&w=800&h=450" },
      { type: "article", outlet: "NDTV", url: "https://www.ndtv.com/world-news/flydubai-flight-fz1073-incident-live-updates-indian-pilot-smit-machchhar-omani-co-pilot-crash-attempt-tabuk-landing-dubai-uae-netanyahu-trump-iran-war-12128203" },
      { type: "article", title: "What happened inside the Flydubai flight to Israel?", outlet: "CNN", date: "2026-09-30", url: "https://www.cnn.com/2026/09/30/middleeast/flydubai-israel-plane-pilot-hijacking-incident-latam-hnk-intl", image: "https://media.cnn.com/api/v1/images/stellar/prod/still-23030774-75135-still.jpg?c=16x9&q=w_800,c_fill" }
    ],
    // Photo supplied by the site owner; credit not yet known. Remove on request from Smit, his family or the photographer.
    image: "images/machchhar-portrait.jpg", imageKind: "portrait", imageAlt: "Captain Smit Machchhar smiling in the cockpit in his pilot's uniform" },
  { id: "sullenberger", name: "Chesley \"Sully\" Sullenberger", role: "Pilot", country: "United States", year: 2009,
    date: "15 January 2009", flight: "US Airways Flight 1549", aircraft: "Airbus A320", place: "Hudson River, New York",
    aboard: 155, survived: 155,
    story: "After a bird strike knocked out both engines shortly after takeoff from LaGuardia, the captain ditched the Airbus A320 on the Hudson River. All 155 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/US_Airways_Flight_1549",
    image: "images/sullenberger.jpg", imageKind: "portrait", imageAlt: "Chesley Sullenberger, official portrait",
    imageCredit: "United States Department of State · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:C.B._Sullenberger,_U.S._Representative_(cropped).jpg" },
  { id: "skiles", name: "Jeffrey Skiles", role: "Pilot", country: "United States", year: 2009,
    date: "15 January 2009", flight: "US Airways Flight 1549", aircraft: "Airbus A320", place: "Hudson River, New York",
    aboard: 155, survived: 155,
    story: "First officer on the 'Miracle on the Hudson'. He worked through the engine-restart checklist while the captain flew the glide to the river. All 155 aboard survived.",
    source: "https://en.wikipedia.org/wiki/US_Airways_Flight_1549",
    image: "images/skiles.jpg", imageKind: "portrait", imageAlt: "Jeffrey Skiles",
    imageCredit: "Susan Ruggles from Milwaukee, USA · CC BY 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Protest_0108_(50939932336)_(Jeffrey_Skiles).jpg" },
  { id: "shults", name: "Tammie Jo Shults", role: "Pilot", country: "United States", year: 2018,
    date: "17 April 2018", flight: "Southwest Airlines Flight 1380", aircraft: "Boeing 737-700", place: "Philadelphia",
    aboard: 148, survived: 147,
    story: "A former US Navy pilot, she landed the Boeing 737 safely in Philadelphia after an uncontained engine failure broke a cabin window and caused a rapid decompression.",
    source: "https://en.wikipedia.org/wiki/Southwest_Airlines_Flight_1380",
    image: "images/shults.jpg", imageKind: "portrait", imageAlt: "Tammie Jo Shults as a US Navy pilot, 1992",
    imageCredit: "Thomas P. Milne, US Navy · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Tammie_Jo_Shults.jpg" },
  { id: "haynes", name: "Al Haynes", role: "Pilot", country: "United States", year: 1989,
    date: "19 July 1989", flight: "United Airlines Flight 232", aircraft: "McDonnell Douglas DC-10", place: "Sioux City, Iowa",
    aboard: 296, survived: 184,
    story: "When an engine failure destroyed all hydraulics on the DC-10, his crew steered using engine thrust alone and reached Sioux City, Iowa. 184 of the 296 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/United_Airlines_Flight_232",
    image: "images/haynes.jpg", imageKind: "portrait", imageAlt: "Al Haynes speaking at an event",
    imageCredit: "Wayne Russell · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Captain_Al_Haynes_(cropped).jpg" },
  { id: "fitch", name: "Dennis Fitch", role: "Pilot", country: "United States", year: 1989,
    date: "19 July 1989", flight: "United Airlines Flight 232", aircraft: "McDonnell Douglas DC-10", place: "Sioux City, Iowa",
    aboard: 296, survived: 184,
    story: "A United training check airman travelling as a passenger, he went to the cockpit and worked the throttles to help steer the crippled DC-10 to Sioux City.",
    source: "https://en.wikipedia.org/wiki/United_Airlines_Flight_232" },
  { id: "williams", name: "Arland D. Williams Jr.", role: "Passenger", country: "United States", year: 1982,
    date: "13 January 1982", flight: "Air Florida Flight 90", aircraft: "Boeing 737-200", place: "Potomac River, Washington, D.C.",
    aboard: 79, survived: 5,
    story: "After the crash into the icy Potomac River, he repeatedly passed the rescue helicopter's lifeline to other survivors. He drowned before he could be rescued himself.",
    source: "https://en.wikipedia.org/wiki/Air_Florida_Flight_90",
    image: "images/williams.jpg", imageKind: "portrait", imageAlt: "Arland D. Williams Jr. in his 1957 graduation photograph from The Citadel",
    imageCredit: "The Citadel · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Arland-D.-Williams-1957-senior-yearbook-photos-768x1024.jpg" },
  { id: "flight93", name: "Passengers and crew of Flight 93", role: "Passenger", country: "United States", year: 2001,
    newsQuery: "United Airlines Flight 93",
    date: "11 September 2001", flight: "United Airlines Flight 93", aircraft: "Boeing 757-200", place: "Shanksville, Pennsylvania",
    story: "On September 11, passengers and crew fought back against the hijackers. The aircraft crashed near Shanksville, Pennsylvania, short of its intended target.",
    source: "https://en.wikipedia.org/wiki/United_Airlines_Flight_93",
    image: "images/flight93.png", imageKind: "scene", imageAlt: "Map of the route flown by United Airlines Flight 93",
    imageCredit: "MysidOriginal by the 9/11 commission · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:UA93_path.svg" },
  { id: "bhanot", name: "Neerja Bhanot", role: "Cabin crew", country: "India", year: 1986,
    date: "5 September 1986", flight: "Pan Am Flight 73", aircraft: "Boeing 747", place: "Karachi, Pakistan",
    story: "The senior purser alerted the cockpit when the aircraft was hijacked in Karachi and helped passengers escape. She was killed shielding children, and was awarded the Ashoka Chakra posthumously.",
    source: "https://en.wikipedia.org/wiki/Neerja_Bhanot",
    image: "images/bhanot.jpg", imageKind: "portrait", imageAlt: "Neerja Bhanot on a 2004 Indian postage stamp",
    imageCredit: "India Post, Government of India · GODL-India", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Neerja_Bhanot_2004_stamp_of_India.jpg" },
  { id: "piche", name: "Robert Piché", role: "Pilot", country: "Canada", year: 2001,
    date: "24 August 2001", flight: "Air Transat Flight 236", aircraft: "Airbus A330", place: "Lajes, Azores",
    aboard: 306, survived: 306,
    story: "A fuel leak caused both engines of the Airbus A330 to fail over the Atlantic. He glided the aircraft to a landing at Lajes in the Azores, and all 306 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/Air_Transat_Flight_236",
    image: "images/piche.jpg", imageKind: "scene", imageAlt: "The Air Transat Airbus A330 after its emergency landing at Lajes",
    imageCredit: "FAA · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Air_Transat_Flight_236_after_emergency_landing.jpg" },
  { id: "yusupov", name: "Damir Yusupov", role: "Pilot", country: "Russia", year: 2019,
    date: "15 August 2019", flight: "Ural Airlines Flight 178", aircraft: "Airbus A321", place: "Near Zhukovsky, Moscow region",
    aboard: 233, survived: 233,
    story: "After bird strikes damaged both engines just after takeoff near Moscow, he landed the Airbus A321 in a cornfield. All 233 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/Ural_Airlines_Flight_178",
    image: "images/yusupov.jpg", imageKind: "portrait", imageAlt: "Damir Yusupov",
    imageCredit: "Presidential Press Service of Russia · CC BY 4.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Damir_Yusupov.jpg" },
  { id: "liu", name: "Liu Chuanjian", role: "Pilot", country: "China", year: 2018,
    date: "14 May 2018", flight: "Sichuan Airlines Flight 8633", aircraft: "Airbus A319", place: "Chengdu",
    aboard: 128, survived: 128,
    story: "The cockpit windshield blew out at cruising altitude. He flew the Airbus A319 manually in freezing, deafening conditions to a safe landing in Chengdu, and no one aboard was killed.",
    source: "https://en.wikipedia.org/wiki/Sichuan_Airlines_Flight_8633",
    image: "images/liu.jpg", imageKind: "portrait", imageAlt: "Captain Liu Chuanjian speaking in 2024",
    imageCredit: "China News Service · CC BY 4.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Liu_Chuanjian-20240305.png" },
  { id: "moody", name: "Eric Moody", role: "Pilot", country: "United Kingdom", year: 1982,
    date: "24 June 1982", flight: "British Airways Flight 9", aircraft: "Boeing 747-200", place: "Jakarta, Indonesia",
    aboard: 263, survived: 263,
    story: "All four engines of the Boeing 747 failed after it flew through volcanic ash over Indonesia. His crew restarted them and landed in Jakarta, and everyone aboard survived.",
    source: "https://en.wikipedia.org/wiki/British_Airways_Flight_9",
    image: "images/moody.jpg", imageKind: "scene", imageAlt: "British Airways Boeing 747-200, registration G-BDXH",
    imageCredit: "G B_NZ · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:BA_747-200_G-BDXH_at_LHR_(16748337441).jpg" },
  { id: "ogden", name: "Nigel Ogden", role: "Cabin crew", country: "United Kingdom", year: 1990,
    date: "10 June 1990", flight: "British Airways Flight 5390", aircraft: "BAC One-Eleven", place: "Southampton",
    aboard: 87, survived: 87,
    story: "When a cockpit windscreen blew out and the captain was pulled partly out of the aircraft, this flight attendant held on to him until the aircraft landed safely at Southampton.",
    source: "https://en.wikipedia.org/wiki/British_Airways_Flight_5390",
    image: "images/ogden.jpg", imageKind: "scene", imageAlt: "British Airways BAC One-Eleven, registration G-BJRT",
    imageCredit: "Rob Hodgkins · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:G-BJRT_BAC1-11_B.A._BHX_15-07-89_(25566356266).jpg" },
  { id: "atchison", name: "Alastair Atchison", role: "Pilot", country: "United Kingdom", year: 1990,
    date: "10 June 1990", flight: "British Airways Flight 5390", aircraft: "BAC One-Eleven", place: "Southampton",
    aboard: 87, survived: 87,
    story: "With the captain pinned half outside the broken windscreen, the first officer flew the BAC One-Eleven alone to an emergency landing at Southampton. Everyone survived.",
    source: "https://en.wikipedia.org/wiki/British_Airways_Flight_5390",
    image: "images/atchison.jpg", imageKind: "scene", imageAlt: "British Airways BAC One-Eleven, registration G-BJRT",
    imageCredit: "Rob Hodgkins · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:G-BJRT_BAC1-11_B.A._BHX_15-07-89_(25566356266).jpg" },
  { id: "harrison", name: "Barbara Jane Harrison", role: "Cabin crew", country: "United Kingdom", year: 1968,
    date: "8 April 1968", flight: "BOAC Flight 712", aircraft: "Boeing 707", place: "London Heathrow",
    aboard: 127, survived: 122,
    story: "When an engine fire broke out after takeoff from Heathrow, she helped passengers escape the burning aircraft and died trying to save others. She was awarded the George Cross posthumously.",
    source: "https://en.wikipedia.org/wiki/Barbara_Jane_Harrison",
    image: "images/harrison.jpg", imageKind: "scene", imageAlt: "Memorial plaque to Jane Harrison in St Laurence's churchyard",
    imageCredit: "David Rogers · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Jane_Harrison_Memorial_-_geograph.org.uk_-_1170236.jpg" },
  { id: "de-crespigny", name: "Richard de Crespigny", role: "Pilot", country: "Australia", year: 2010,
    date: "4 November 2010", flight: "Qantas Flight 32", aircraft: "Airbus A380", place: "Singapore",
    aboard: 469, survived: 469,
    story: "An uncontained engine failure caused severe damage to the Airbus A380 after takeoff from Singapore. His crew worked through dozens of system failures and landed safely, and all 469 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/Qantas_Flight_32",
    image: "images/de-crespigny.jpg", imageKind: "portrait", imageAlt: "Richard de Crespigny, March 2011",
    imageCredit: "RicharddeCrep · CC BY-SA 4.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Richard_de_Crespigny,_March_2011.jpg" },
  { id: "abate", name: "Leul Abate", role: "Pilot", country: "Ethiopia", year: 1996,
    date: "23 November 1996", flight: "Ethiopian Airlines Flight 961", aircraft: "Boeing 767-200ER", place: "Off Grande Comore, Comoros",
    aboard: 175, survived: 50,
    story: "Hijackers forced the Boeing 767 to fly until it ran out of fuel. He ditched it in the sea off the Comoros. 50 of the 175 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/Ethiopian_Airlines_Flight_961",
    image: "images/abate.jpg", imageKind: "scene", imageAlt: "Ethiopian Airlines Boeing 767, registration ET-AIZ, at London Heathrow in July 1996",
    imageCredit: "Hugh McMillan · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:ET-AIZ,_at_London_Heathrow,_England_July_1996.jpg" },
  { id: "derickson", name: "Uli Derickson", role: "Cabin crew", country: "Germany", year: 1985,
    date: "14 June 1985", flight: "TWA Flight 847", aircraft: "Boeing 727", place: "Beirut and Algiers",
    story: "During the hijacking, the purser used her German to talk with the hijackers, calmed and protected passengers, and paid for fuel in Algiers with her own credit card.",
    source: "https://en.wikipedia.org/wiki/Uli_Derickson",
    image: "images/derickson.jpg", imageKind: "scene", imageAlt: "Trans World Airlines Boeing 727",
    imageCredit: "Jon Proctor · GFDL 1.2", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Boeing_727-231(Adv),_Trans_World_Airlines_(TWA)_JP5958649.jpg" }
];

if (typeof module !== "undefined") module.exports = HEROES; // lets scripts/build.mjs read the list
