// AirSkyHero hero list. To add a hero, copy one entry, change the fields, and keep the commas.
// id: short unique name used in links (airskyhero.com/#hero-<id>). role: Pilot, Cabin crew or Passenger.
// image fields are optional; only use freely licensed images (e.g. Wikimedia Commons) and keep the credit.
// aboard / survived are optional: leave them out where the count is not well established.
// featured: true puts a hero in the "Featured hero" spot at the top of the page. teaser: a short summary shown there,
//   worded differently from story so the home page and the hero's page don't repeat each other.
// developing: true marks a recent event whose details may still change.
// news: optional coverage shown in the hero's story, newest first. type is "video" (YouTube link, plays in the page)
//   or "article". title, date (YYYY-MM-DD) and image (the article's preview picture) are optional, but give videos their YouTube
//   upload date so Google can list them as videos. top: true marks a main story (a major development such as an award
//   or official finding); for 3 days after its date it is listed first in the home page's Latest news. Every hero also gets "latest news" search links automatically.
//   Pictures should not repeat: if an article reuses a photo already on the page, use another freely licensed
//   picture saved in images/news/ and add imageCredit: "Author · Licence".
//   Before adding a story, search every hero's news (not only this hero's) for the same story from another outlet:
//   heroes from the same flight often share coverage, and the home page's Latest news would list it twice.
// newsQuery: optional search words for those links (defaults to the hero's name and flight).
// seoTitle / seoDescription: optional search-result title and summary for the hero's page (default: name, flight, year / start of the story).
// timeline: optional [{ date, text, sources: [urls] }] and faq: optional [{ q, a, sources: [urls] }], shown on the hero's page.
//   Keep both to facts confirmed by the linked sources.
// slug: optional page address (airskyhero.com/<slug>/); defaults to the name, e.g. "smit-machchhar".
// After editing this file, run "npm run build" to update the hero pages, share images and sitemap.
const HEROES = [
  { id: "machchhar", name: "Smit Machchhar", role: "Pilot", country: "India", year: 2026,
    featured: true, developing: true,
    teaser: "Badly hurt in a cockpit attack on a Dubai to Tel Aviv flight, he got the cockpit door open so passengers and crew could stop his attacker. All 174 passengers survived.",
    date: "30 September 2026", flight: "flydubai Flight 1073", aircraft: "Boeing 737 MAX 8", place: "Tabuk, Saudi Arabia",
    story: "Captain Smit Machchhar was flying flydubai Flight 1073 from Dubai to Tel Aviv when he was attacked in the cockpit by the first officer and the aircraft went into a rapid descent. The UAE Attorney-General has since said the first officer, who used the cockpit crash axe, attempted to carry out a terrorist act. Though seriously injured, Machchhar opened the cockpit door, allowing passengers and crew to restrain the attacker. Off-duty pilots travelling on board took over and the Boeing 737 MAX 8 landed safely at Tabuk, Saudi Arabia, with all 174 passengers alive. A resolution introduced in the US House of Representatives honours him and the crew and passengers. Gujarat has announced its Vishisht Gujarat Garima Award and ₹25 lakh for him, and Mankind Pharma ₹1 crore for him and his family. The investigation is ongoing.",
    source: "https://en.wikipedia.org/wiki/Flydubai_Flight_1073",
    seoTitle: "Captain Smit Machchhar: flydubai FZ1073 story, timeline and news",
    seoDescription: "How Captain Smit Machchhar fought off a cockpit attack on flydubai Flight FZ1073 and saved 174 passengers: timeline, who helped, awards and latest news.",
    timeline: [
      { date: "30 September 2026", text: "flydubai Flight FZ1073 leaves Dubai for Tel Aviv, a Boeing 737 MAX 8 with 174 passengers, captained by Smit Machchhar.",
        sources: ["https://en.wikipedia.org/wiki/Flydubai_Flight_1073", "https://www.cnn.com/2026/09/30/middleeast/flydubai-israel-plane-pilot-hijacking-incident-latam-hnk-intl"] },
      { date: "30 September 2026", text: "The first officer attacks him in the cockpit with the crash axe and the jet plunges about 16,000 feet in under a minute. Badly wounded, Machchhar opens the cockpit door and passengers and crew rush in to restrain the attacker.",
        sources: ["https://www.aljazeera.com/news/2026/10/2/12-minutes-of-madness-how-flydubai-pilot-passengers-saved-plane-midfall", "https://www.cnbc.com/2026/10/01/dubai-israel-flight-pilot-crash-indian.html", "https://www.tribuneindia.com/news/captain-smit-machchhar/us-house-bill-honours-indian-pilot-smit-machchhar-for-thwarting-attempted-terror-attack-on-flydubai-flight"] },
      { date: "30 September 2026", text: "Off-duty flydubai pilots travelling on board take the controls and land at Tabuk, Saudi Arabia. Everyone on board survives.",
        sources: ["https://www.thenationalnews.com/business/aviation/2026/10/02/flydubai-flight-fz1073-puts-airline-deadheading-in-the-spotlight/", "https://www.cnbc.com/2026/10/01/dubai-israel-flight-pilot-crash-indian.html"] },
      { date: "1 October 2026", text: "He is flown from Saudi Arabia to the UAE for treatment. The UAE Attorney-General orders an investigation, including any link to terrorism.",
        sources: ["https://www.cnn.com/2026/10/01/world/live-news/flydubai-flight-israel-pilot-passengers-intl", "https://gulfnews.com/uae/government/uae-attorney-general-orders-investigation-into-flydubai-flight-incident-1.500694536", "https://www.thenationalnews.com/news/uae/2026/10/01/flydubai-uae-investigation-terrorist-activity/"] },
      { date: "1 October 2026", text: "Gujarat announces the Vishisht Gujarat Garima Award and a ₹25 lakh reward for him.",
        sources: ["https://www.outlookindia.com/national/gujarat-to-honour-pilot-smit-machchhar-with-visisht-gujarat-garima-award", "https://www.deccanchronicle.com/nation/gujarat-announces-state-award-for-pilot-machchhar-prayers-held-at-somnath-for-recovery-1992209"] },
      { date: "2 October 2026", text: "Prime Minister Narendra Modi speaks to him by video call in hospital. Mankind Pharma announces ₹1 crore for him and his family.",
        sources: ["https://www.business-standard.com/india-news/pm-modi-speaks-to-flydubai-pilot-smit-machchhar-hails-his-bravery-126100200301_1.html", "https://theprint.in/feature/smit-machchhar-recalls-flydubai-attack-in-call-with-pm-modi-i-was-fighting-for-my-life/3060007/", "https://theprint.in/feature/mankind-pharma-captain-smit-machchhar-1-crore-extraordinary-courage/3060475/"] },
      { date: "3 October 2026", text: "The UAE Attorney-General says the first officer attempted to carry out a terrorist act.",
        sources: ["https://www.aljazeera.com/news/2026/10/3/flydubai-co-pilot-stabbed-pilot-with-crash-axe-in-terrorist-attack-uae", "https://gulfnews.com/business/aviation/flydubai-fz1073-timeline-how-cockpit-incident-became-a-terror-investigation-1.500696919"] },
      { date: "5 October 2026", text: "Two Israeli officials say the first officer told interrogators he planned the attack before joining flydubai. A resolution honouring Machchhar and the crew and passengers is introduced in the US House of Representatives.",
        sources: ["https://www.cbc.ca/news/world/flydubai-copilot-attack-planned-9.7369232", "https://www.irishtimes.com/world/middle-east/2026/10/05/flydubai-co-pilot-planned-to-crash-into-israels-ben-gurion-airport-israeli-officials/", "https://www.tribuneindia.com/news/captain-smit-machchhar/us-house-bill-honours-indian-pilot-smit-machchhar-for-thwarting-attempted-terror-attack-on-flydubai-flight"] },
      { date: "8 October 2026", text: "Israel's President Isaac Herzog says Machchhar will receive Israel's Presidential Award for Civilian Heroism once he recovers, as he presents the Presidential Medal for Civilian Heroism to six passengers from the flight.",
        sources: ["https://www.tribuneindia.com/news/bravery/indian-flydubai-pilot-smit-machchhar-to-receive-israels-presidential-award-for-civilian-heroism", "https://www.outlookindia.com/international/pilot-smit-machchhar-to-receive-israels-presidential-award-for-civilian-heroism"] },
      { date: "9 October 2026", text: "The UAE Attorney-General says the investigation found the first officer planned to seize the plane and crash it into the passenger terminal at Ben Gurion Airport. A forensic report found head injuries to the captain consistent with an axe. The first officer reportedly says he acted alone, and investigators are checking for accomplices.",
        sources: ["https://gulfnews.com/business/aviation/flydubai-incident-uae-probe-reveals-what-happened-inside-the-cockpit-1.500705052", "https://tribuneindia.com/news/9-11/uae-attorney-general-says-flydubai-co-pilot-planned-suicide-attack-on-tel-aviv-airport"] },
      { date: "10 October 2026", text: "India's National Investigation Agency registers a case under the Anti-Hijacking Act and the Unlawful Activities (Prevention) Act over the attack, and says it will look into a possible wider conspiracy.",
        sources: ["https://theprint.in/india/nia-invokes-uapa-anti-hijacking-act-in-flydubai-pilot-attack-case-to-probe-larger-conspiracy/3067756"] }
    ],
    faq: [
      { q: "Who is Captain Smit Machchhar?", a: "An Indian airline pilot who has flown the Boeing 737 for flydubai as a captain since 2022. Before that he spent about 11 years at SpiceJet in India. He has around 9,750 flying hours.",
        sources: ["https://www.theweek.in/news/middle-east/2026/09/30/smit-machchhar-flydubai-pilot-spiceject-hijack-scare-israel-uae-saudi.amp.html", "https://businesstoday.in/india/story/smit-machchhar-former-spicejet-pilot-at-the-centre-of-flydubai-mid-air-emergency-558914-2026-09-30", "https://www.outlookindia.com/national/who-is-captain-smit-machchhar-indian-pilot-at-centre-of-flydubai-flight-emergency"] },
      { q: "What happened on flydubai Flight FZ1073?", a: "On 30 September 2026, on the way from Dubai to Tel Aviv, the first officer attacked Captain Machchhar with the cockpit crash axe and the plane went into a steep dive. Though badly hurt, he opened the cockpit door so passengers and crew could stop the attacker. Off-duty flydubai pilots landed the plane at Tabuk, Saudi Arabia, and all 174 passengers survived.",
        sources: ["https://en.wikipedia.org/wiki/Flydubai_Flight_1073", "https://www.aljazeera.com/news/2026/10/2/12-minutes-of-madness-how-flydubai-pilot-passengers-saved-plane-midfall", "https://www.cnbc.com/2026/10/01/dubai-israel-flight-pilot-crash-indian.html"] },
      { q: "Who else helped save the flight?", a: "Passengers Tzvika Manes, Yaniv Hayun, Asaf Rajuan and Dr Shota Musayev overpowered the first officer, and Musayev treated the captain's wounds. Tali Manes raised the alarm. Kenyan flight attendants David Kimotho and John Muchina gave him first aid, and off-duty flydubai pilots landed the plane.",
        sources: ["https://www.timesofisrael.com/liveblog_entry/herzog-recommends-four-men-from-flydubai-flight-fz1073-for-presidential-award-for-civilian-heroism/", "https://www.israelhayom.com/2026/10/05/flydubai-kenyan-flight-attendants-captain-swahili/", "https://www.thenationalnews.com/business/aviation/2026/10/02/flydubai-flight-fz1073-puts-airline-deadheading-in-the-spotlight/"] },
      { q: "How is Captain Machchhar now?", a: "He is being treated in hospital in the UAE. India's ambassador said on 1 October that he was \"speaking, smiling and laughing\", and on 6 October India's embassy said he \"continues to make steady progress and is regaining his health\". On 9 October reports said he was still recovering in hospital in Abu Dhabi.",
        sources: ["https://www.outlookindia.com/international/pilot-smit-machchhar-to-receive-israels-presidential-award-for-civilian-heroism", "https://www.outlookindia.com/international/speaking-smiling-laughing-indian-envoy-gives-health-update-on-captain-smit-machchhar", "https://www.moneycontrol.com/world/don-t-sleep-we-need-you-dentist-recalls-45-minute-battle-to-save-smit-machchhar-i-don-t-want-to-die-here-article-14046242.html","https://www.etvbharat.com/en/international/live-blog--flydubai-incident-live-updates-captain-smit-machchhar-indian-pilot-saves-lives-israel-saudi-arabia-uae-benjamin-netanyahu-enn26100102127"] },
      { q: "How has he been honoured?", a: "Gujarat announced its Vishisht Gujarat Garima Award and ₹25 lakh, Mankind Pharma ₹1 crore, and a resolution honouring him was introduced in the US House of Representatives. On 8 October Israel's President Isaac Herzog announced that he will receive Israel's Presidential Award for Civilian Heroism. Prime Minister Modi spoke to him by video call. Reports say he may be considered for the Ashoka Chakra, but nothing has been announced.",
        sources: ["https://www.outlookindia.com/national/gujarat-to-honour-pilot-smit-machchhar-with-visisht-gujarat-garima-award", "https://theprint.in/feature/mankind-pharma-captain-smit-machchhar-1-crore-extraordinary-courage/3060475/", "https://www.tribuneindia.com/news/captain-smit-machchhar/us-house-bill-honours-indian-pilot-smit-machchhar-for-thwarting-attempted-terror-attack-on-flydubai-flight", "https://www.tribuneindia.com/news/india/captain-smit-machchhar-may-get-ashoka-chakra-for-mid-air-heroics/", "https://www.tribuneindia.com/news/bravery/indian-flydubai-pilot-smit-machchhar-to-receive-israels-presidential-award-for-civilian-heroism"] },
      { q: "How do you spell his name?", a: "Smit Machchhar. It is sometimes written Machchar or Machhar." },
      { q: "Is this Smit Machchhar's official website?", a: "No. AirSkyHero is an independent site about heroes of the sky. It is not run by or connected to Captain Machchhar, his family or flydubai." }
    ],
    news: [
      { type: "article", title: "NIA invokes UAPA, Anti-Hijacking Act in FlyDubai pilot attack case; to probe larger conspiracy", outlet: "ThePrint", date: "2026-10-10", top: true, url: "https://theprint.in/india/nia-invokes-uapa-anti-hijacking-act-in-flydubai-pilot-attack-case-to-probe-larger-conspiracy/3067756" },
      { type: "article", title: "UAE Attorney-General says flydubai co-pilot planned suicide attack on Tel Aviv airport", outlet: "The Tribune", date: "2026-10-10", top: true, url: "https://tribuneindia.com/news/9-11/uae-attorney-general-says-flydubai-co-pilot-planned-suicide-attack-on-tel-aviv-airport" },
      { type: "article", title: "US Congressman Krishnamoorthi honours Indian pilot Smit Machchhar in Congressional Record for bravery during flydubai cockpit attack", outlet: "The Tribune", date: "2026-10-10", url: "https://www.tribuneindia.com/news/usa-news/us-congressman-krishnamoorthi-honours-indian-pilot-smit-machchhar-in-congressional-record-for-bravery-during-flydubai-cockpit-attack" },
      { type: "article", title: "Indian flydubai pilot Smit Machchhar to receive Israel’s Presidential Award for Civilian Heroism", outlet: "The Tribune", date: "2026-10-09", top: true, url: "https://www.tribuneindia.com/news/bravery/indian-flydubai-pilot-smit-machchhar-to-receive-israels-presidential-award-for-civilian-heroism" },
      { type: "article", title: "Captain Smit Machchhar on feet again, walks 10 steps as recovery continues after Flydubai flight attack", outlet: "WION", date: "2026-10-08", url: "https://www.wionews.com/india-news/captain-smit-machchhar-on-feet-again-takes-steps-as-recovery-continues-after-flydubai-flight-attack-1791418941442" },
      { type: "article", title: "Hero flydubai captain was always ‘two steps’ ahead when on duty", outlet: "The National", date: "2026-10-08", url: "https://www.thenationalnews.com/news/uae/2026/10/08/hero-flydubai-captain-was-always-two-steps-ahead-when-on-duty/" },
      { type: "article", title: "Captain Smit Machchhar showing steady health improvement: MEA", outlet: "Telangana Today", date: "2026-10-07", url: "https://telanganatoday.com/captain-smit-machchhar-showing-steady-health-improvement-mea" },
      { type: "article", title: "Flydubai captain says copilot asked to pray, then struck him from behind; describes exactly how he opened cockpit door", outlet: "The Times of Israel", date: "2026-10-04", url: "https://www.timesofisrael.com/flydubai-captain-says-copilot-asked-to-pray-then-struck-him-from-behind-describes-exactly-how-he-opened-cockpit-door/" },
      { type: "article", title: "'Couldn't sleep all night': Captain Smit Machchhar's family recounts flydubai ordeal", outlet: "Khaleej Times", date: "2026-10-04", url: "https://www.khaleejtimes.com/uae/indian-pilot-smit-machchhar-family-emotional-flydubai-incident" },
      { type: "video", title: "Big Health Update On Smit Machchhar: Indian Pilot Recovering Well In UAE", outlet: "CNN-News18", date: "2026-10-03", url: "https://www.youtube.com/watch?v=L2ijp7-o1bc" },
      { type: "article", title: "'Captain Courageous': SRK, Salman, Ranveer & Other Stars Salute Smit Machchhar", outlet: "Deccan Chronicle", date: "2026-10-03", url: "https://www.deccanchronicle.com/entertainment/captain-courageous-srk-salman-ranveer-bollywood-stars-salute-captain-smit-machchhar-1992813" },
      { type: "video", title: "Captain Smit Machchhar's Wife Says, 'Very Delighted That PM Modi Spoke To Him'", outlet: "Moneycontrol", date: "2026-10-02", url: "https://www.youtube.com/watch?v=ry80jwnw2nA" },
      { type: "video", title: "UAE Crown Prince Sheikh Hamdan visits Captain Smit Machchhar in hospital", outlet: "DD India", date: "2026-10-03", url: "https://www.youtube.com/watch?v=xEnbfqlHN3g" },
      { type: "article", title: "US House bill honours Indian pilot Smit Machchhar for thwarting attempted terror attack on flydubai flight", outlet: "The Tribune", date: "2026-10-06", url: "https://www.tribuneindia.com/news/captain-smit-machchhar/us-house-bill-honours-indian-pilot-smit-machchhar-for-thwarting-attempted-terror-attack-on-flydubai-flight", image: "images/news/us-capitol.jpg", imageCredit: "Architect of the Capitol · Public domain" },
      { type: "article", title: "Captain Machchhar to Receive Mother Teresa Memorial Award 2026", outlet: "Deccan Chronicle", date: "2026-10-05", url: "https://www.deccanchronicle.com/news/current-affairs/captain-machchhar-to-receive-mother-teresa-memorial-award-2026-1993234" },
      { type: "article", title: "Confer pilot Smit Machchhar with Ashoka Chakra: Gurugram Bar Association writes to PM", outlet: "ThePrint", date: "2026-10-06", url: "https://theprint.in/india/confer-pilot-smit-machchhar-with-ashoka-chakra-gurugram-bar-association-writes-to-pm/3063651/" },
      { type: "article", title: "Co-pilot planned Flydubai attack before joining airline, two Israeli officials say", outlet: "US News (Reuters)", date: "2026-10-05", url: "https://www.usnews.com/news/world/articles/2026-10-05/co-pilot-planned-flydubai-attack-before-hired-by-airline-two-israeli-officials-say", image: "images/news/ben-gurion-t3.jpg", imageCredit: "Djampa · CC BY-SA 4.0" },
      { type: "article", title: "FlyDubai co-pilot allegedly planned to crash Israel-bound jet at Ben Gurion Airport", outlet: "Fox News", url: "https://www.foxnews.com/world/flydubai-copilot-allegedly-planned-crash-israel-bound-jet-ben-gurion-airport", image: "images/news/ben-gurion-hall.jpg", imageCredit: "Ralf Roletschek · GFDL 1.2" },
      { type: "article", title: "Flydubai co-pilot attacked captain with crash axe in ‘terrorist act’: UAE", outlet: "Al Jazeera", date: "2026-10-03", url: "https://www.aljazeera.com/news/2026/10/3/flydubai-co-pilot-stabbed-pilot-with-crash-axe-in-terrorist-attack-uae", image: "https://www.aljazeera.com/wp-content/uploads/2026/10/reuters_6ac0a7cd-1791010765.jpg?resize=800%2C450" },
      { type: "article", title: "From cockpit altercation to ‘terrorist act’: flydubai FZ1073 timeline", outlet: "Gulf News", date: "2026-10-03", url: "https://gulfnews.com/business/aviation/flydubai-fz1073-timeline-how-cockpit-incident-became-a-terror-investigation-1.500696919", image: "https://media.assettype.com/gulfnews%2F2026-10-03%2Fjp2miflh%2FUntitled-2.jpg?w=800&ar=16%3A9&auto=format%2Ccompress&mode=crop" },
      { type: "article", title: "'The last push, Smit': FlyDubai captain Smit Machchhar recounts harrowing cockpit attack", outlet: "ABC News", url: "https://abcnews.com/International/push-smit-flydubai-captain-smit-machchhar-recounts-harrowing/story?id=136944166", image: "images/news/cockpit-from-cabin.jpg", imageCredit: "Excounter · CC BY-SA 4.0" },
      { type: "article", title: "Hero FlyDubai pilot says he was 'fighting for my life' as plane plunged after copilot attack", outlet: "Fox News", url: "https://www.foxnews.com/world/hero-flydubai-pilot-fighting-life-plane-plunged-copilot-attack", image: "images/news/dubai-airport-t2.jpg", imageCredit: "Ravi Dwivedi · CC BY-SA 4.0" },
      { type: "article", title: "Captain Smit Machchhar may get Ashoka Chakra for mid-air heroics", outlet: "The Tribune", date: "2026-10-02", url: "https://www.tribuneindia.com/news/india/captain-smit-machchhar-may-get-ashoka-chakra-for-mid-air-heroics/", image: "images/news/rashtrapati-bhavan.jpg", imageCredit: "Diego Delso · CC BY-SA 4.0" },
      { type: "article", title: "'I was fighting for my life': Indian pilot hailed as hero recalls FlyDubai cockpit attack", outlet: "CBC News", date: "2026-10-02", url: "https://www.cbc.ca/news/world/flydubai-pilot-interview-hospital-9.7366522" },
      { type: "article", title: "FlyDubai captain tells India's leader how he saved himself and 173 others while fighting for his own life", outlet: "CBS News", date: "2026-10-02", url: "https://www.cbsnews.com/news/flydubai-flight-incident-pilot-tells-india-leader-modi-his-story/" },
      { type: "article", title: "Flydubai pilot Smit Machchhar: I couldn't let everybody else die", outlet: "CNN", date: "2026-10-02", url: "https://www.cnn.com/2026/10/02/middleeast/i-couldnt-let-everybody-else-die-says-hero-flydubai-pilot-smit-machchhar", image: "https://media.cnn.com/api/v1/images/stellar/videothumbnails/27947023-11227013-generated-thumbnail.jpg?c=16x9&q=w_800,c_fill" },
      { type: "article", title: "'Hero To World': Netanyahu Invites Smit Machchhar To Independence Day Event", outlet: "NDTV", url: "https://www.ndtv.com/world-news/hero-to-entire-world-netanyahu-invites-flydubai-hero-to-israel-independence-day-event-12135282", image: "https://c.ndtvimg.com/2026-10/8g4svmcc_netanyahu-afp_625x300_01_October_26.jpeg?im=FeatureCrop,algorithm=dnn,width=800,height=450" },
      { type: "article", title: "Mankind Pharma honours Captain Smit Machchhar with Rs 1 crore for 'extraordinary courage'", outlet: "ThePrint", date: "2026-10-02", url: "https://theprint.in/feature/mankind-pharma-captain-smit-machchhar-1-crore-extraordinary-courage/3060475/", image: "images/news/mankind-logo.jpg", imageCredit: "Natasharajraj · CC BY-SA 4.0" },
      { type: "article", title: "GCAA commends flydubai Captain Machchhar Smit, crew and passengers after FZ1073 incident", outlet: "Gulf News", date: "2026-10-02", url: "https://gulfnews.com/business/aviation/gcaa-commends-flydubai-captain-machchhar-smit-crew-and-passengers-after-fz1073-incident-1.500696490" },
      { type: "article", title: "Indian pilot Smit Machchhar recalls battling for lives in cockpit", outlet: "Gulf News", url: "https://gulfnews.com/business/aviation/flydubai-pilot-reveals-what-happened-in-cockpit-i-couldnt-let-everybody-else-die-1.500695904", image: "images/news/737-max-cockpit.jpg", imageCredit: "GeoMancer448 · CC BY 4.0" },
      { type: "article", title: "Capt Smit Machchhar's wife recounts horrifying moments as she heard of flydubai cockpit attack", outlet: "The Tribune", url: "https://www.tribuneindia.com/news/world/was-devastated-didnt-have-mental-capacity-to-react-capt-smit-machchhars-wife-recounts-horrifying-moments-as-she-heard-of-flydubai-cockpit-attack/amp/", image: "images/news/tabuk-airport.jpg", imageCredit: "م سعود العنزي · CC BY-SA 4.0" },
      { type: "article", title: "'India and Israel should be very proud': US hails Indian pilot, Israeli passengers", outlet: "The Tribune", url: "https://www.tribuneindia.com/news/india/india-and-israel-should-be-very-proud-us-hails-indian-pilot-israeli-passengers-for-averting-flydubai-terror-attack/", image: "images/news/india-israel.jpg", imageCredit: "Prime Minister's Office, India · GODL-India" },
      { type: "article", title: "UAE Deputy PM meets Smit Machchhar at Abu Dhabi hospital, says country's leadership praises his courage", outlet: "Daily Jagran", url: "https://www.thedailyjagran.com/world/news/uae-deputy-pm-meets-smit-machchhar-at-abu-dhabi-hospital-says-countrys-leadership-praises-his-courage-10331440", image: "images/news/abu-dhabi-night.jpg", imageCredit: "Nepenthes · CC BY-SA 3.0" },
      { type: "article", title: "Captain Smit Machchhar 'in good health and recovering well', says India's embassy in the UAE", outlet: "ETV Bharat", url: "https://www.etvbharat.com/en/international/live-blog--flydubai-incident-live-updates-captain-smit-machchhar-indian-pilot-saves-lives-israel-saudi-arabia-uae-benjamin-netanyahu-enn26100102127", image: "images/news/abu-dhabi-flag.jpg", imageCredit: "Clint Ian Pinto · CC BY-SA 4.0" },
      { type: "article", title: "Who is Smit Machchhar? Flydubai pilot stabbed identified by Israel PM Netanyahu", outlet: "Newsweek", url: "https://www.newsweek.com/who-is-capt-smit-machchhar-flydubai-pilot-flight-fz1073-12509226", image: "images/news/flydubai-737-max.jpg", imageCredit: "Anna Zvereva · CC BY-SA 2.0" },
      { type: "article", title: "What we know about the pilot hailed as a hero for averting crash of Israel-bound plane", outlet: "NBC News", date: "2026-10-01", url: "https://www.nbcnews.com/world/middle-east/smit-machchhar-pilot-hero-averting-crash-israel-plane-rcna600874", image: "images/news/india-flag.jpg", imageCredit: "Sisheer Philip · CC BY-SA 4.0" },
      { type: "article", title: "Flydubai Indian pilot Smit Machchhar hailed as hero after cockpit stabbing", outlet: "The Washington Post", date: "2026-10-01", url: "https://www.washingtonpost.com/world/2026/10/01/flydubai-indian-pilot-smit-machchhar-hailed-hero-after-cockpit-stabbing/", image: "images/news/dubai-skyline.jpg", imageCredit: "Jpbowen · CC BY-SA 4.0" },
      { type: "article", title: "'Speaking, Smiling & Laughing': Indian Envoy Gives Health Update On Captain Smit Machchhar", outlet: "Outlook India", date: "2026-10-01", url: "https://www.outlookindia.com/international/speaking-smiling-laughing-indian-envoy-gives-health-update-on-captain-smit-machchhar", image: "images/news/red-fort-flag.jpg", imageCredit: "Denimedger · CC BY-SA 3.0" },
      { type: "article", title: "What we're learning about the FlyDubai co-pilot who allegedly stabbed the captain and tried to crash the plane", outlet: "CBS News", date: "2026-10-01", url: "https://www.cbsnews.com/news/flydubai-plane-attempted-crash-hijacking-israel-dubai-what-to-know/", image: "images/news/737-panel-night.jpg", imageCredit: "Shawn from Airdrie, Canada · CC BY-SA 2.0" },
      { type: "article", title: "Captain Smit Machchhar: The ‘jovial’ pilot and father who thwarted the Flydubai attacker", outlet: "CNN", date: "2026-10-01", url: "https://www.cnn.com/2026/10/01/india/india-captain-smit-machchhar-flydubai-intl-hnk", image: "images/news/spicejet-737.jpg", imageCredit: "Oleg Yunakov · CC BY-SA 4.0" },
      { type: "article", title: "Pilot suspected of Flydubai attack transferred to UAE as investigation unfolds", outlet: "CNN", date: "2026-10-01", url: "https://www.cnn.com/2026/10/01/world/live-news/flydubai-flight-israel-pilot-passengers-intl", image: "https://media.cnn.com/api/v1/images/stellar/prod/2026-09-30t152357z-2093004972-rc2rtnaksbz0-rtrmadp-3-israel-gulf-flight-passengers-tabuk.JPG?c=16x9&q=w_800,c_fill" },
      { type: "article", title: "Former GoAir pilot recalls meeting with braveheart Smit Machchhar", outlet: "ThePrint", date: "2026-10-01", url: "https://theprint.in/india/former-goair-pilot-recalls-meeting-with-braveheart-smit-machchhar/3059208/" },
      { type: "article", title: "'As long as you walk out of the aircraft safely – that’s what I want': flydubai hero pilot", outlet: "The National", date: "2026-10-01", url: "https://www.thenationalnews.com/news/uae/2026/10/01/as-long-as-you-walk-out-of-the-aircraft-safely-thats-what-i-want-flydubai-hero-pilot/" },
      { type: "article", title: "Flydubai co-pilot ‘assaulted’ captain before landing: initial Saudi probe", outlet: "Al Jazeera", date: "2026-10-01", url: "https://www.aljazeera.com/news/2026/10/1/flydubai-co-pilot-assaulted-captain-before-landing-initial-saudi-probe", image: "https://www.aljazeera.com/wp-content/uploads/2026/10/afp_6abebf3c75ec-1790885692.jpg?resize=800%2C450" },
      { type: "article", title: "Passengers and crew foil co-pilot's apparent attempt to crash FlyDubai flight to Israel", outlet: "CNBC", date: "2026-10-01", url: "https://www.cnbc.com/2026/10/01/dubai-israel-flight-pilot-crash-indian.html", image: "https://image.cnbcfm.com/api/v1/image/108370773-1790813698247-gettyimages-2297373318-_erm5466.jpeg?v=1790813718&w=800&h=450" },
      { type: "article", title: "Flydubai Incident Highlights: Israel Minister Calls For Naming Lounge At Main Airport After Smit Machchhar", outlet: "NDTV", url: "https://www.ndtv.com/world-news/flydubai-flight-fz1073-incident-live-updates-indian-pilot-smit-machchhar-omani-co-pilot-crash-attempt-tabuk-landing-dubai-uae-netanyahu-trump-iran-war-12128203", image: "https://c.ndtvimg.com/2026-10/sglmqrng_flydubai_625x300_01_October_26.jpeg?im=FeatureCrop,algorithm=dnn,width=800,height=450" },
      { type: "article", title: "What happened inside the Flydubai flight to Israel?", outlet: "CNN", date: "2026-09-30", url: "https://www.cnn.com/2026/09/30/middleeast/flydubai-israel-plane-pilot-hijacking-incident-latam-hnk-intl", image: "https://media.cnn.com/api/v1/images/stellar/prod/still-23030774-75135-still.jpg?c=16x9&q=w_800,c_fill" },
      { type: "article", title: "Flydubai pilot Smit Machchhar reportedly aided rescue efforts while wounded", outlet: "The Jerusalem Post", date: "2026-09-30", url: "https://www.jpost.com/international/article-910230" }
    ],
    // Photo supplied by the site owner; credit not yet known. Remove on request from Smit, his family or the photographer.
    image: "images/machchhar-portrait.jpg", imageKind: "portrait", imageAlt: "Captain Smit Machchhar smiling in the cockpit in his pilot's uniform" },
  { id: "fz1073-passengers", name: "Passengers of flydubai Flight 1073", role: "Passenger", country: "Israel", year: 2026,
    developing: true,
    date: "30 September 2026", flight: "flydubai Flight 1073", aircraft: "Boeing 737 MAX 8", place: "Tabuk, Saudi Arabia",
    story: "When the wounded captain, Smit Machchhar, managed to open the cockpit door of flydubai Flight 1073, passengers rushed in. Tali Manes had raised the alarm after hearing the struggle while waiting outside the front toilet for her daughter. Her husband Tzvika Manes, Yaniv Hayun, Asaf Rajuan and Dr Shota Musayev got into the cockpit and overpowered the first officer, and Musayev treated the captain's wounds, while off-duty flydubai pilots took over and landed the plane at Tabuk. On 8 October Israel's President Isaac Herzog presented the Presidential Medal for Civilian Heroism to six of them: Tali and Tzvika Manes, Yaniv Hayun, Dr Shota Musayev, Asaf Rajuan and Or Pardilov.",
    source: "https://www.timesofisrael.com/liveblog_entry/herzog-recommends-four-men-from-flydubai-flight-fz1073-for-presidential-award-for-civilian-heroism/",
    news: [
      { type: "article", title: "Pilot Smit Machchhar To Receive Israel's Presidential Award For Civilian Heroism", outlet: "Outlook", date: "2026-10-09", url: "https://www.outlookindia.com/international/pilot-smit-machchhar-to-receive-israels-presidential-award-for-civilian-heroism" },
      { type: "article", title: "'Don't sleep, we need you': Dentist recalls 45-minute battle to save Smit Machchhar", outlet: "Moneycontrol", date: "2026-10-07", url: "https://www.moneycontrol.com/world/don-t-sleep-we-need-you-dentist-recalls-45-minute-battle-to-save-smit-machchhar-i-don-t-want-to-die-here-article-14046242.html", image: "images/news/first-aid.jpg", imageCredit: "Friedrich Haag · CC BY-SA 4.0" },
      { type: "article", title: "What really happened aboard flydubai FZ1073 during attempted terror attack", outlet: "Khaleej Times", url: "https://www.khaleejtimes.com/business/aviation/what-really-happened-flydubai-fz1073-terror-attack", image: "images/news/ben-gurion.jpg", imageCredit: "Deror avi · Attribution" },
      { type: "article", title: "How a 6-year-old's bathroom request helped avert disaster on flydubai flight to Tel Aviv", outlet: "WION", date: "2026-10-03", url: "https://www.wionews.com/world/how-a-6-year-old-nina-manes-bathroom-request-helped-avert-disaster-on-flydubai-flight-to-tel-aviv-1791026268249", image: "images/news/lavatory.jpg", imageCredit: "AhmadElq · CC BY-SA 4.0" },
      { type: "article", title: "Flydubai flight FZ1073 puts airline ‘deadheading’ in spotlight", outlet: "The National", date: "2026-10-02", url: "https://www.thenationalnews.com/business/aviation/2026/10/02/flydubai-flight-fz1073-puts-airline-deadheading-in-the-spotlight/", image: "https://www.thenationalnews.com/resizer/v2/6OH5FCN5GDHRSD4JDPDYXFZIUE.jpg?auth=97ff18e8556fd60a6af2b5bf0f9bd36310b742c9e13e80aa70a09d8044ed1046&smart=true&width=800&height=450" },
      { type: "article", title: "12 minutes of madness: How Flydubai pilot, passengers saved plane midfall", outlet: "Al Jazeera", date: "2026-10-02", url: "https://www.aljazeera.com/news/2026/10/2/12-minutes-of-madness-how-flydubai-pilot-passengers-saved-plane-midfall", image: "images/news/flydubai-cabin.jpg", imageCredit: "Kgbo · CC BY-SA 4.0" },
      { type: "article", title: "Flydubai passengers helped crew control FZ1073 incident, UAE aviation authority reveals", outlet: "Arabian Business", url: "https://www.arabianbusiness.com/business/transport/flydubai-passengers-helped-crew-control-fz1073-incident-uae-aviation-authority-reveals", image: "images/news/737-cockpit-flight.jpg", imageCredit: "John Christian Fjellestad · CC BY 4.0" },
      { type: "article", title: "Herzog recommends four men from flydubai flight FZ1073 for Presidential Award for Civilian Heroism", outlet: "Times of Israel", date: "2026-10-01", url: "https://www.timesofisrael.com/liveblog_entry/herzog-recommends-four-men-from-flydubai-flight-fz1073-for-presidential-award-for-civilian-heroism/", image: "images/news/herzog.jpg", imageCredit: "Avi Ohayon · CC BY-SA 3.0" },
      { type: "article", title: "Flydubai Flight FZ1073 heroes: who are the 5 people who helped avert a mid-air disaster?", outlet: "Sunday Guardian", url: "https://sundayguardianlive.com/world/flydubai-flight-fz1073-heroes-who-are-the-5-people-who-helped-avert-a-mid-air-disaster-indian-pilot-plumber-banker-businessman-and-dentist-296430/", image: "https://sundayguardianlive.com/wp-content/uploads/2026/10/flydubai-flight-fz1073-heroes-who-helped-avert-a-mid-air-disaster-on-the-dubai-tel-aviv-flight.png" }
    ],
    image: "images/flydubai-1073-group.jpg", imageKind: "scene", imageAlt: "A flydubai Boeing 737 MAX 8 seen from below in flight",
    imageCredit: "Marcxosm · CC BY 4.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Flydubai_737_8-MAX_(A6-FMN)_taking_off_from_Pisa_airport,_P4_parking,_2024.jpg" },
  { id: "fz1073-crew", name: "David Kimotho and John Muchina", role: "Cabin crew", country: "Kenya", year: 2026,
    developing: true,
    date: "30 September 2026", flight: "flydubai Flight 1073", aircraft: "Boeing 737 MAX 8", place: "Tabuk, Saudi Arabia",
    story: "Lead flight attendant David Kimotho and his colleague John Muchina, both from Kenya, gave first aid to Captain Smit Machchhar as he lay bleeding on the cabin floor of flydubai Flight 1073 after the cockpit attack, speaking to each other in Swahili as they checked on him and kept him talking. Kimotho also kept order in the cabin, telling panicking passengers to sit down. The UAE's aviation authority praised the crew's \"remarkable courage and speed of response\".",
    source: "https://www.israelhayom.com/2026/10/05/flydubai-kenyan-flight-attendants-captain-swahili/",
    news: [
      { type: "article", title: "Kenyan crew's untold role in Flydubai drama", outlet: "Israel Hayom", date: "2026-10-05", url: "https://www.israelhayom.com/2026/10/05/flydubai-kenyan-flight-attendants-captain-swahili/", image: "images/news/dubai-airport-dxb.jpg", imageCredit: "Andy Mabbett · CC BY-SA 4.0" }
    ],
    image: "images/news/kenya-flag.jpg", imageKind: "scene", imageAlt: "The flag of Kenya",
    imageCredit: "Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Flag_of_Kenya.svg" },
  { id: "sullenberger", name: "Chesley \"Sully\" Sullenberger", role: "Pilot", country: "United States", year: 2009,
    date: "15 January 2009", flight: "US Airways Flight 1549", aircraft: "Airbus A320", place: "Hudson River, New York",
    aboard: 155, survived: 155,
    story: "After a bird strike knocked out both engines shortly after takeoff from LaGuardia, the captain ditched the Airbus A320 on the Hudson River. All 155 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/US_Airways_Flight_1549",
    image: "images/sullenberger.jpg", imageKind: "portrait", imageAlt: "Chesley Sullenberger, official portrait",
    imageCredit: "United States Department of State · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:C.B._Sullenberger,_U.S._Representative_(cropped).jpg" },
  { id: "skiles", name: "Jeffrey Skiles", role: "Pilot", country: "United States", year: 2009,
    date: "15 January 2009", flight: "US Airways Flight 1549", aircraft: "Airbus A320", place: "Hudson River, New York",
    aboard: 155, survived: 155,
    story: "First officer on the 'Miracle on the Hudson'. He worked through the engine-restart checklist while the captain flew the glide to the river. All 155 aboard survived.",
    source: "https://en.wikipedia.org/wiki/US_Airways_Flight_1549",
    image: "images/skiles.jpg", imageKind: "portrait", imageAlt: "Jeffrey Skiles",
    imageCredit: "Susan Ruggles from Milwaukee, USA · CC BY 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Protest_0108_(50939932336)_(Jeffrey_Skiles).jpg" },
  { id: "shults", name: "Tammie Jo Shults", role: "Pilot", country: "United States", year: 2018,
    date: "17 April 2018", flight: "Southwest Airlines Flight 1380", aircraft: "Boeing 737-700", place: "Philadelphia",
    aboard: 148, survived: 147,
    story: "A former US Navy pilot, she landed the Boeing 737 safely in Philadelphia after an uncontained engine failure broke a cabin window and caused a rapid decompression.",
    source: "https://en.wikipedia.org/wiki/Southwest_Airlines_Flight_1380",
    image: "images/shults.jpg", imageKind: "portrait", imageAlt: "Tammie Jo Shults as a US Navy pilot, 1992",
    imageCredit: "Thomas P. Milne, US Navy · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Tammie_Jo_Shults.jpg" },
  { id: "haynes", name: "Al Haynes", role: "Pilot", country: "United States", year: 1989,
    date: "19 July 1989", flight: "United Airlines Flight 232", aircraft: "McDonnell Douglas DC-10", place: "Sioux City, Iowa",
    aboard: 296, survived: 184,
    story: "When an engine failure destroyed all hydraulics on the DC-10, his crew steered using engine thrust alone and reached Sioux City, Iowa. 184 of the 296 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/United_Airlines_Flight_232",
    image: "images/haynes.jpg", imageKind: "portrait", imageAlt: "Al Haynes speaking at an event",
    imageCredit: "Wayne Russell · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Captain_Al_Haynes_(cropped).jpg" },
  { id: "fitch", name: "Dennis Fitch", role: "Pilot", country: "United States", year: 1989,
    date: "19 July 1989", flight: "United Airlines Flight 232", aircraft: "McDonnell Douglas DC-10", place: "Sioux City, Iowa",
    aboard: 296, survived: 184,
    story: "A United training check airman travelling as a passenger, he went to the cockpit and worked the throttles to help steer the crippled DC-10 to Sioux City.",
    source: "https://en.wikipedia.org/wiki/United_Airlines_Flight_232",
    image: "images/fitch.jpg", imageKind: "scene", imageAlt: "N1819U, the United Airlines DC-10 later lost as Flight 232, at Newark in 1980",
    imageCredit: "Paul Seymour · CC BY-SA 4.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:N1819U_McDonnell_Douglas_DC-10-10_United_Airlines,_Newark_International_Airport_1980.jpg" },
  { id: "williams", name: "Arland D. Williams Jr.", role: "Passenger", country: "United States", year: 1982,
    date: "13 January 1982", flight: "Air Florida Flight 90", aircraft: "Boeing 737-200", place: "Potomac River, Washington, D.C.",
    aboard: 79, survived: 5,
    story: "After the crash into the icy Potomac River, he repeatedly passed the rescue helicopter's lifeline to other survivors. He drowned before he could be rescued himself.",
    source: "https://en.wikipedia.org/wiki/Air_Florida_Flight_90",
    image: "images/williams.jpg", imageKind: "portrait", imageAlt: "Arland D. Williams Jr. in his 1957 graduation photograph from The Citadel",
    imageCredit: "The Citadel · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Arland-D.-Williams-1957-senior-yearbook-photos-768x1024.jpg" },
  { id: "flight93", name: "Passengers and crew of Flight 93", role: "Passenger", country: "United States", year: 2001,
    newsQuery: "United Airlines Flight 93",
    date: "11 September 2001", flight: "United Airlines Flight 93", aircraft: "Boeing 757-200", place: "Shanksville, Pennsylvania",
    story: "On September 11, passengers and crew fought back against the hijackers. The aircraft crashed near Shanksville, Pennsylvania, short of its intended target.",
    source: "https://en.wikipedia.org/wiki/United_Airlines_Flight_93",
    image: "images/flight93.png", imageKind: "scene", imageAlt: "Map of the route flown by United Airlines Flight 93",
    imageCredit: "MysidOriginal by the 9/11 commission · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:UA93_path.svg" },
  { id: "bhanot", name: "Neerja Bhanot", role: "Cabin crew", country: "India", year: 1986,
    date: "5 September 1986", flight: "Pan Am Flight 73", aircraft: "Boeing 747", place: "Karachi, Pakistan",
    story: "The senior purser alerted the cockpit when the aircraft was hijacked in Karachi and helped passengers escape. She was killed shielding children, and was awarded the Ashoka Chakra posthumously.",
    source: "https://en.wikipedia.org/wiki/Neerja_Bhanot",
    image: "images/bhanot.jpg", imageKind: "portrait", imageAlt: "Neerja Bhanot on a 2004 Indian postage stamp",
    imageCredit: "India Post, Government of India · GODL-India", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Neerja_Bhanot_2004_stamp_of_India.jpg" },
  { id: "piche", name: "Robert Piché", role: "Pilot", country: "Canada", year: 2001,
    date: "24 August 2001", flight: "Air Transat Flight 236", aircraft: "Airbus A330", place: "Lajes, Azores",
    aboard: 306, survived: 306,
    story: "A fuel leak caused both engines of the Airbus A330 to fail over the Atlantic. He glided the aircraft to a landing at Lajes in the Azores, and all 306 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/Air_Transat_Flight_236",
    image: "images/piche.jpg", imageKind: "scene", imageAlt: "The Air Transat Airbus A330 after its emergency landing at Lajes",
    imageCredit: "FAA · Public domain", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Air_Transat_Flight_236_after_emergency_landing.jpg" },
  { id: "yusupov", name: "Damir Yusupov", role: "Pilot", country: "Russia", year: 2019,
    date: "15 August 2019", flight: "Ural Airlines Flight 178", aircraft: "Airbus A321", place: "Near Zhukovsky, Moscow region",
    aboard: 233, survived: 233,
    story: "After bird strikes damaged both engines just after takeoff near Moscow, he landed the Airbus A321 in a cornfield. All 233 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/Ural_Airlines_Flight_178",
    image: "images/yusupov.jpg", imageKind: "portrait", imageAlt: "Damir Yusupov",
    imageCredit: "Presidential Press Service of Russia · CC BY 4.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Damir_Yusupov.jpg" },
  { id: "liu", name: "Liu Chuanjian", role: "Pilot", country: "China", year: 2018,
    date: "14 May 2018", flight: "Sichuan Airlines Flight 8633", aircraft: "Airbus A319", place: "Chengdu",
    aboard: 128, survived: 128,
    story: "The cockpit windshield blew out at cruising altitude. He flew the Airbus A319 manually in freezing, deafening conditions to a safe landing in Chengdu, and no one aboard was killed.",
    source: "https://en.wikipedia.org/wiki/Sichuan_Airlines_Flight_8633",
    image: "images/liu.jpg", imageKind: "portrait", imageAlt: "Captain Liu Chuanjian speaking in 2024",
    imageCredit: "China News Service · CC BY 4.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Liu_Chuanjian-20240305.png" },
  { id: "moody", name: "Eric Moody", role: "Pilot", country: "United Kingdom", year: 1982,
    date: "24 June 1982", flight: "British Airways Flight 9", aircraft: "Boeing 747-200", place: "Jakarta, Indonesia",
    aboard: 263, survived: 263,
    story: "All four engines of the Boeing 747 failed after it flew through volcanic ash over Indonesia. His crew restarted them and landed in Jakarta, and everyone aboard survived.",
    source: "https://en.wikipedia.org/wiki/British_Airways_Flight_9",
    image: "images/moody.jpg", imageKind: "scene", imageAlt: "British Airways Boeing 747-200, registration G-BDXH",
    imageCredit: "G B_NZ · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:BA_747-200_G-BDXH_at_LHR_(16748337441).jpg" },
  { id: "ogden", name: "Nigel Ogden", role: "Cabin crew", country: "United Kingdom", year: 1990,
    date: "10 June 1990", flight: "British Airways Flight 5390", aircraft: "BAC One-Eleven", place: "Southampton",
    aboard: 87, survived: 87,
    story: "When a cockpit windscreen blew out and the captain was pulled partly out of the aircraft, this flight attendant held on to him until the aircraft landed safely at Southampton.",
    source: "https://en.wikipedia.org/wiki/British_Airways_Flight_5390",
    image: "images/ogden.jpg", imageKind: "scene", imageAlt: "British Airways BAC One-Eleven, registration G-BJRT",
    imageCredit: "Rob Hodgkins · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:G-BJRT_BAC1-11_B.A._BHX_15-07-89_(25566356266).jpg" },
  { id: "atchison", name: "Alastair Atchison", role: "Pilot", country: "United Kingdom", year: 1990,
    date: "10 June 1990", flight: "British Airways Flight 5390", aircraft: "BAC One-Eleven", place: "Southampton",
    aboard: 87, survived: 87,
    story: "With the captain pinned half outside the broken windscreen, the first officer flew the BAC One-Eleven alone to an emergency landing at Southampton. Everyone survived.",
    source: "https://en.wikipedia.org/wiki/British_Airways_Flight_5390",
    image: "images/atchison.jpg", imageKind: "scene", imageAlt: "British Airways BAC One-Eleven, registration G-BJRT",
    imageCredit: "Rob Hodgkins · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:G-BJRT_BAC1-11_B.A._BHX_15-07-89_(25566356266).jpg" },
  { id: "harrison", name: "Barbara Jane Harrison", role: "Cabin crew", country: "United Kingdom", year: 1968,
    date: "8 April 1968", flight: "BOAC Flight 712", aircraft: "Boeing 707", place: "London Heathrow",
    aboard: 127, survived: 122,
    story: "When an engine fire broke out after takeoff from Heathrow, she helped passengers escape the burning aircraft and died trying to save others. She was awarded the George Cross posthumously.",
    source: "https://en.wikipedia.org/wiki/Barbara_Jane_Harrison",
    image: "images/harrison.jpg", imageKind: "scene", imageAlt: "Memorial plaque to Jane Harrison in St Laurence's churchyard",
    imageCredit: "David Rogers · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Jane_Harrison_Memorial_-_geograph.org.uk_-_1170236.jpg" },
  { id: "de-crespigny", name: "Richard de Crespigny", role: "Pilot", country: "Australia", year: 2010,
    date: "4 November 2010", flight: "Qantas Flight 32", aircraft: "Airbus A380", place: "Singapore",
    aboard: 469, survived: 469,
    story: "An uncontained engine failure caused severe damage to the Airbus A380 after takeoff from Singapore. His crew worked through dozens of system failures and landed safely, and all 469 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/Qantas_Flight_32",
    image: "images/de-crespigny.jpg", imageKind: "portrait", imageAlt: "Richard de Crespigny, March 2011",
    imageCredit: "RicharddeCrep · CC BY-SA 4.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Richard_de_Crespigny,_March_2011.jpg" },
  { id: "abate", name: "Leul Abate", role: "Pilot", country: "Ethiopia", year: 1996,
    date: "23 November 1996", flight: "Ethiopian Airlines Flight 961", aircraft: "Boeing 767-200ER", place: "Off Grande Comore, Comoros",
    aboard: 175, survived: 50,
    story: "Hijackers forced the Boeing 767 to fly until it ran out of fuel. He ditched it in the sea off the Comoros. 50 of the 175 people aboard survived.",
    source: "https://en.wikipedia.org/wiki/Ethiopian_Airlines_Flight_961",
    image: "images/abate.jpg", imageKind: "scene", imageAlt: "Ethiopian Airlines Boeing 767, registration ET-AIZ, at London Heathrow in July 1996",
    imageCredit: "Hugh McMillan · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:ET-AIZ,_at_London_Heathrow,_England_July_1996.jpg" },
  { id: "lemine", name: "Ahmedou Mohamed Lemine", role: "Pilot", country: "Mauritania", year: 2007,
    newsQuery: "Air Mauritanie hijacking 2007 pilot",
    date: "15 February 2007", flight: "Air Mauritanie, Nouakchott to Gran Canaria", aircraft: "Boeing 737", place: "Gran Canaria, Spain",
    aboard: 79, survived: 79,
    story: "Soon after takeoff from Nouakchott, a lone gunman with two pistols hijacked the Air Mauritanie Boeing 737 and demanded to be flown to France. The captain, a 20-year veteran of the airline, said there was not enough fuel and headed for Gran Canaria. Realising the hijacker did not speak French, he used the public address system to tell passengers in French that he would brake hard on landing and then speed up, and asked women and children to move to the back. When the hijacker fell in the aisle, flight attendants threw boiling water from the coffee machine at him and about ten passengers held him down until Spanish police boarded. About 20 people had minor injuries from the braking; no one was killed.",
    source: "https://www.nbcnews.com/id/wbna17183946",
    news: [
      { type: "article", title: "Fast-thinking pilot fools hijacker", outlet: "NBC News (AP)", date: "2007-02-16", url: "https://www.nbcnews.com/id/wbna17183946" },
      { type: "article", title: "Mauritanian hijacker sought asylum", outlet: "Al Jazeera", date: "2007-02-16", url: "https://www.aljazeera.com/news/2007/2/16/mauritanian-hijacker-sought-asylum" },
      { type: "article", title: "Jet's pilot shakes up hijacker", outlet: "The Philadelphia Inquirer", date: "2007-02-17", url: "https://www.inquirer.com/philly/news/nation_world/20070217_Jets_pilot_shakes_up_hijacker.html" }
    ],
    image: "images/mauritania-hijack.jpg", imageKind: "scene", imageAlt: "An Air Mauritanie Boeing 737 at Gran Canaria airport in 2002",
    imageCredit: "Aero Icarus · CC BY-SA 2.0", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Air_Mauritanie_Boeing_737-200;_F-GCSL@LPA,_February_2002_(4845259900).jpg" },
  { id: "derickson", name: "Uli Derickson", role: "Cabin crew", country: "Germany", year: 1985,
    date: "14 June 1985", flight: "TWA Flight 847", aircraft: "Boeing 727", place: "Beirut and Algiers",
    story: "During the hijacking, the purser used her German to talk with the hijackers, calmed and protected passengers, and paid for fuel in Algiers with her own credit card.",
    source: "https://en.wikipedia.org/wiki/Uli_Derickson",
    image: "images/derickson.jpg", imageKind: "scene", imageAlt: "Trans World Airlines Boeing 727",
    imageCredit: "Jon Proctor · GFDL 1.2", imageCreditUrl: "https://commons.wikimedia.org/wiki/File:Boeing_727-231(Adv),_Trans_World_Airlines_(TWA)_JP5958649.jpg" }
];

if (typeof module !== "undefined") module.exports = HEROES; // lets scripts/build.mjs read the list
