// Builds the parts of the site that come from heroes.js. Run with: npm run build
//   <slug>/index.html   one page per hero (airskyhero.com/smit-machchhar/), readable by Google
//   share/<slug>.jpg     1200x630 preview image shown when a hero's link is shared
//   share/home.jpg       preview image for the home page
//   sitemap.xml          every page, for Google Search Console
// Preview images need Google Chrome (or set CHROME_PATH); pages and sitemap are written either way.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const HEROES = require(path.join(ROOT, "heroes.js"));
const HELPERS = require(path.join(ROOT, "helpers.js"));
const KINDNESS = require(path.join(ROOT, "kindness.js"));
const KIND_SLUG = "acts-of-kindness";
const { SITE, esc, heroSlug, heroPath, heroUrl, shareImage, newsHtml, helpersHtml, developingText, shareHtml, splitNews } = require(path.join(ROOT, "news.js"));

const MARK = `<!-- Generated by scripts/build.mjs from heroes.js. Edit heroes.js, then run "npm run build". -->`;
const abs = p => (p && !/^https?:/.test(p) ? "/" + p.replace(/^\//, "") : p);
const initials = name => name.replace(/["(].*?[")]/g, "").split(/\s+/).filter(w => /^[A-Z]/.test(w)).map(w => w[0]).slice(0, 2).join("");
const clip = (s, n) => (s.length <= n ? s : s.slice(0, s.lastIndexOf(" ", n - 1)) + "…");
const write = (file, data) => {
  const full = path.join(ROOT, file);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  if (fs.existsSync(full) && Buffer.compare(fs.readFileSync(full), Buffer.from(data)) === 0) return false;
  fs.writeFileSync(full, data);
  return true;
};

// Same order as the home page list: by country, then year.
const ordered = [...HEROES].sort((a, b) => a.country.localeCompare(b.country) || a.year - b.year);
const slugs = new Set();
for (const h of ordered) {
  const s = heroSlug(h);
  if (s === KIND_SLUG) throw new Error(`"${s}" is the Acts of kindness page. Give this hero another slug in heroes.js.`);
  if (slugs.has(s)) throw new Error(`Two heroes have the page address "${s}". Give one of them slug: "..." in heroes.js.`);
  slugs.add(s);
}

// Every news link belongs on one hero's page only, so no two pages list the same story.
{
  const seen = new Map();
  for (const h of HEROES) for (const n of h.news || []) {
    if (seen.has(n.url)) throw new Error(`"${n.url}" is in the news of both ${seen.get(n.url)} and ${h.name}. Keep it on one of them in heroes.js.`);
    seen.set(n.url, h.name);
  }
}

/* ---------- Hero pages ---------- */
const PLANE = `<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M21 16v-2l-8-5V3.5a1.5 1.5 0 0 0-3 0V9l-8 5v2l8-2.5V19l-2 1.5V22l3.5-1 3.5 1v-1.5L13 19v-5.5l8 2.5z"/></svg>`;

const HEADER = `<header>
  <div class="wrap">
    <a class="logo" href="/" aria-label="AirSkyHero home">
      ${PLANE}
      <span>Air<b>Sky</b>Hero</span>
    </a>
    <nav aria-label="Main">
      <a href="/#map-section">Map</a>
      <a href="/#heroes">Heroes</a>
      <a href="/acts-of-kindness/">Kindness</a>
      <a href="/what-passengers-can-do/">Safety</a>
      <a href="/#about">About</a>
    </nav>
  </div>
</header>`;

const heroCard = h => `
        <a class="card" href="${heroPath(h)}">
          <div class="thumb">${h.image
            ? `<img src="${esc(abs(h.image))}" alt="${esc(h.imageAlt || "")}" class="${h.imageKind === "portrait" ? "face" : ""}" loading="lazy" width="640" height="360">`
            : `<span class="initials" aria-hidden="true">${esc(initials(h.name))}</span>`}</div>
          <h4>${esc(h.name)}</h4>
          <div class="tags"><span class="tag">${esc(h.role)}</span><span class="tag">${h.year}</span></div>
          <p class="flight">${esc(h.flight)}</p>
          <span class="more">Read story →</span>
        </a>`;

// Other heroes from the same flight first, then the same country, then the closest in time.
function related(h) {
  const rank = o => (o.flight === h.flight ? 0 : o.country === h.country ? 1 : 2) * 1e4 + Math.abs(o.year - h.year);
  return HEROES.filter(o => o !== h).sort((a, b) => rank(a) - rank(b)).slice(0, 3);
}

// Optional sections from heroes.js: timeline (dated events with numbered source links) and faq (questions and answers).
const srcLinks = urls => (urls || []).length ? ` <span class="h-src">Sources: ${urls.map((u, i) =>
  `<a href="${esc(u)}" target="_blank" rel="noopener" title="${esc(u.replace(/^https?:\/\/(www\.)?/, "").split("/")[0])}">${i + 1}</a>`).join(" ")}</span>` : "";
const timelineHtml = h => !h.timeline ? "" : `    <h2 class="hp-h">Timeline</h2>
    <ol class="timeline">
${h.timeline.map(t => `      <li><span class="tl-date">${esc(t.date)}</span><span class="tl-text">${esc(t.text)}${srcLinks(t.sources)}</span></li>`).join("\n")}
    </ol>
`;
const faqHtml = h => !h.faq ? "" : `    <h2 class="hp-h">Questions people ask</h2>
    <div class="faq">
${h.faq.map(f => `      <details><summary>${esc(f.q)}</summary><p>${esc(f.a)}${srcLinks(f.sources)}</p></details>`).join("\n")}
    </div>
`;

function heroPage(h, i) {
  const title = `${h.seoTitle || `${h.name}: ${h.flight} (${h.year})`} | AirSkyHero`;
  const description = h.seoDescription || clip(h.story, 158);
  const prev = ordered[i - 1], next = ordered[i + 1];
  const facts = [
    ["Flight", h.flight], ["Date", h.date], ["Aircraft", h.aircraft], ["Location", h.place],
    ...(h.aboard ? [["Survivors", `${h.survived} of ${h.aboard} aboard`]] : [])
  ];
  const { videos } = splitNews(h);
  const ld = {
    "@context": "https://schema.org", "@type": "Article",
    headline: `${h.name}: ${h.flight}`, description, url: heroUrl(h), image: shareImage(h),
    about: { "@type": h.role === "Passenger" && /^Passengers/.test(h.name) ? "Thing" : "Person", name: h.name, nationality: h.country },
    publisher: { "@type": "Organization", name: "AirSkyHero", url: SITE },
    ...(videos.length ? { video: videos.map(v => ({ "@type": "VideoObject", name: v.title || v.outlet, embedUrl: v.url })) } : {})
  };
  const faqLd = h.faq && {
    "@context": "https://schema.org", "@type": "FAQPage",
    mainEntity: h.faq.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } }))
  };
  return `<!doctype html>
${MARK}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<meta name="theme-color" content="#0b1118">
<link rel="canonical" href="${heroUrl(h)}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="AirSkyHero">
<meta property="og:title" content="${esc(`${h.name}: ${h.flight}`)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${heroUrl(h)}">
<meta property="og:image" content="${shareImage(h)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${esc(`${h.name}, ${h.role}, ${h.flight}`)}">
<meta name="twitter:card" content="summary_large_image">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="stylesheet" href="/site.css">
<script type="application/ld+json">${JSON.stringify(ld).replace(/</g, "\\u003c")}</script>
${faqLd ? `<script type="application/ld+json">${JSON.stringify(faqLd).replace(/</g, "\\u003c")}</script>\n` : ""}</head>
<body>

${HEADER}

<main class="wrap hero-page">
  <p class="crumbs"><a href="/">Home</a> › <a href="/#heroes">Heroes</a> › ${esc(h.country)}</p>
  <article>
    <div class="hp-head">
      <p class="eyebrow">${esc(h.role)} · ${esc(h.country)}</p>
      <h1>${esc(h.name)}</h1>
      <div class="tags"><span class="tag">${esc(h.flight)}</span><span class="tag">${h.year}</span>${h.developing ? '<span class="badge-live">Developing story</span>' : ""}</div>
    </div>
${h.image ? `    <figure class="hp-photo">
      <img src="${esc(abs(h.image))}" alt="${esc(h.imageAlt || "")}">
${h.imageCredit ? `      <figcaption>Photo: <a href="${esc(h.imageCreditUrl || "")}" target="_blank" rel="noopener">${esc(h.imageCredit)}</a></figcaption>\n` : ""}    </figure>
` : ""}    <dl class="facts">
${facts.map(([k, v]) => `      <div class="fact"><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join("\n")}
    </dl>
${h.developing ? `    <p class="developing">${esc(developingText(h))}</p>\n` : ""}    <p class="hp-story">${esc(h.story)}</p>
${timelineHtml(h)}${helpersHtml(h, HELPERS, HEROES).replace(/^\n/, "")}${HELPERS[h.flight] ? "\n" : ""}${faqHtml(h)}    <p class="hp-source">Source: <a href="${esc(h.source)}" target="_blank" rel="noopener">${esc(h.source.replace(/^https?:\/\/(www\.)?/, ""))} ↗</a></p>
    <p class="hp-guide">If something goes wrong on your flight: <a href="/what-passengers-can-do/">what passengers can do, close by or farther away →</a></p>
    ${shareHtml(h)}
    <section class="news" aria-labelledby="d-news-h">${newsHtml(h)}
    </section>
  </article>

  <section class="hp-more" aria-labelledby="more-h">
    <h2 id="more-h">More heroes</h2>
    <div class="grid">${related(h).map(heroCard).join("")}
    </div>
    <nav class="hp-pager" aria-label="Previous and next hero">
      <span>${prev ? `<a href="${heroPath(prev)}">← ${esc(prev.name)}</a>` : ""}</span>
      <span>${next ? `<a href="${heroPath(next)}">${esc(next.name)} →</a>` : ""}</span>
    </nav>
    <a class="hp-home" href="/#heroes">See all heroes on the world map →</a>
  </section>
</main>

<script src="/news.js"></script>
<script data-goatcounter="https://airskyhero.goatcounter.com/count" async src="https://gc.zgo.at/count.js"></script>
<script>
if ("serviceWorker" in navigator && location.protocol === "https:") navigator.serviceWorker.register("/sw.js");
</script>
</body>
</html>
`;
}

let changed = 0;
ordered.forEach((h, i) => { if (write(`${heroSlug(h)}/index.html`, heroPage(h, i))) changed++; });

// Remove pages of heroes that were deleted or renamed (only folders this script made).
for (const d of fs.readdirSync(ROOT, { withFileTypes: true })) {
  const page = path.join(ROOT, d.name, "index.html");
  if (d.isDirectory() && !slugs.has(d.name) && d.name !== KIND_SLUG && fs.existsSync(page) && fs.readFileSync(page, "utf8").includes(MARK)) {
    fs.rmSync(path.join(ROOT, d.name), { recursive: true });
    console.log(`Removed old page /${d.name}/`);
  }
}
console.log(`Hero pages: ${ordered.length} (${changed} updated)`);

/* ---------- Acts of kindness page ---------- */
// World map on the page, drawn in the browser like the home page map. Clicking a country jumps to its stories.
const KIND_MAP_JS = `// Our country names -> names used by the world-atlas map data.
const MAP_NAME = { "United States": "United States of America" };
const NUDGE = { "United States": [-98, 39], "Canada": [-100, 57] };
function pick(c) {
  document.querySelectorAll("#map .land.has").forEach(p => p.classList.toggle("selected", p.dataset.c === c));
  location.hash = KIND[c].id;
}
addEventListener("DOMContentLoaded", async () => {
  const status = document.getElementById("map-status"), tip = document.getElementById("tip");
  try {
    const world = await d3.json("https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json");
    const features = topojson.feature(world, world.objects.countries).features;
    const ours = Object.fromEntries(Object.keys(KIND).map(c => [MAP_NAME[c] || c, c]));
    const projection = d3.geoNaturalEarth1().fitExtent([[8, 8], [952, 492]], { type: "Sphere" });
    const path = d3.geoPath(projection);
    const svg = d3.select("#map");
    svg.append("path").attr("class", "sphere").attr("d", path({ type: "Sphere" }));
    svg.append("path").attr("class", "grat").attr("d", path(d3.geoGraticule10()));
    const label = c => c + " · " + KIND[c].n + (KIND[c].n === 1 ? " story" : " stories");
    svg.append("g").selectAll("path").data(features).join("path")
      .attr("d", path)
      .attr("class", d => "land" + (ours[d.properties.name] ? " has" : ""))
      .attr("data-c", d => ours[d.properties.name] || null)
      .attr("tabindex", d => ours[d.properties.name] ? 0 : null)
      .attr("role", d => ours[d.properties.name] ? "button" : null)
      .attr("aria-label", d => ours[d.properties.name] ? label(ours[d.properties.name]) : null)
      .filter(d => ours[d.properties.name])
      .on("click", (e, d) => pick(ours[d.properties.name]))
      .on("keydown", (e, d) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); pick(ours[d.properties.name]); } })
      .on("mousemove", (e, d) => {
        const box = document.getElementById("map").parentElement.getBoundingClientRect();
        tip.textContent = label(ours[d.properties.name]);
        tip.style.left = (e.clientX - box.left + 12) + "px";
        tip.style.top = (e.clientY - box.top + 12) + "px";
        tip.style.opacity = 1;
      })
      .on("mouseleave", () => { tip.style.opacity = 0; });
    svg.append("g").selectAll("text")
      .data(features.filter(d => ours[d.properties.name]))
      .join("text").attr("class", "pin")
      .attr("transform", d => {
        const c = ours[d.properties.name];
        const [x, y] = NUDGE[c] ? projection(NUDGE[c]) : path.centroid(d);
        return "translate(" + x + "," + (y + 4) + ")";
      })
      .text(d => KIND[ours[d.properties.name]].n);
    status.remove();
  } catch (err) {
    status.className = "map-error";
    status.textContent = "The map couldn't load. Use the country buttons below instead.";
  }
});`;

// airskyhero.com/acts-of-kindness/: stories from kindness.js, grouped by country.
{
  const ids = new Set();
  for (const k of KINDNESS) {
    if (ids.has(k.id)) throw new Error(`Two kindness stories have the id "${k.id}" in kindness.js.`);
    ids.add(k.id);
    if ((k.sources || []).length < 3) throw new Error(`Kindness story "${k.id}" needs at least three sources in kindness.js.`);
  }
  const countries = [...new Set(KINDNESS.map(k => k.country))].sort();
  const cid = c => "k-" + heroSlug({ name: c });
  const story = k => `
        <li class="k-card" id="${esc(k.id)}">
          <h3>${esc(k.title)}</h3>
          <p class="k-meta">${[k.who, k.airline, k.flight, k.date].filter(Boolean).map(esc).join(" · ")}</p>
          <p>${esc(k.summary)}${srcLinks(k.sources)}</p>
        </li>`;
  const title = "Acts of kindness on aeroplanes, country by country";
  const description = `${KINDNESS.length} true stories of crew and passengers looking after strangers on flights, from ${countries.length} countries, each checked against at least three sources.`;
  const ld = {
    "@context": "https://schema.org", "@type": "CollectionPage", name: title, description, url: `${SITE}/${KIND_SLUG}/`,
    publisher: { "@type": "Organization", name: "AirSkyHero", url: SITE }
  };
  const page = `<!doctype html>
${MARK}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)} | AirSkyHero</title>
<meta name="description" content="${esc(description)}">
<meta name="theme-color" content="#0b1118">
<link rel="canonical" href="${SITE}/${KIND_SLUG}/">
<meta property="og:type" content="article">
<meta property="og:site_name" content="AirSkyHero">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${SITE}/${KIND_SLUG}/">
<meta property="og:image" content="${SITE}/share/home.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="stylesheet" href="/site.css">
<script type="application/ld+json">${JSON.stringify(ld).replace(/</g, "\\u003c")}</script>
</head>
<body>

${HEADER}

<main class="wrap hero-page guide kindness">
  <p class="crumbs"><a href="/">Home</a> › Acts of kindness</p>
  <article>
    <div class="hp-head">
      <p class="eyebrow">Acts of kindness</p>
      <h1>Kindness at 35,000 feet</h1>
    </div>
    <p class="hp-story">Not every hero of the sky lands a broken plane. These are true stories of cabin crew, pilots, passengers and whole towns who looked after strangers on a flight. Every story is checked against at least three independent sources, linked under it.</p>
    <div class="map-box">
      <svg id="map" viewBox="0 0 960 500" role="img" aria-label="World map of acts of kindness by country"></svg>
      <div class="map-loading" id="map-status">Loading map…</div>
      <div class="tooltip" id="tip" aria-hidden="true"></div>
    </div>
    <nav class="k-countries" aria-label="Countries">${countries.map(c =>
      `<a href="#${cid(c)}">${esc(c)} <span>${KINDNESS.filter(k => k.country === c).length}</span></a>`).join("")}</nav>
${countries.map(c => `    <section aria-labelledby="${cid(c)}">
      <h2 id="${cid(c)}">${esc(c)}</h2>
      <ul class="k-list">${KINDNESS.filter(k => k.country === c).sort((a, b) => a.year - b.year).map(story).join("")}
      </ul>
    </section>`).join("\n")}
  </article>
  <a class="hp-home" href="/#heroes">See the heroes of the sky →</a>
</main>

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.9.0/d3.min.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/topojson/3.0.2/topojson.min.js" defer></script>
<script data-goatcounter="https://airskyhero.goatcounter.com/count" async src="https://gc.zgo.at/count.js"></script>
<script>
const KIND = ${JSON.stringify(Object.fromEntries(countries.map(c => [c, { n: KINDNESS.filter(k => k.country === c).length, id: cid(c) }])))};
${KIND_MAP_JS}
if ("serviceWorker" in navigator && location.protocol === "https:") navigator.serviceWorker.register("/sw.js");
</script>
</body>
</html>
`;
  if (write(`${KIND_SLUG}/index.html`, page)) console.log("Acts of kindness page updated");
  console.log(`Acts of kindness: ${KINDNESS.length} stories from ${countries.length} countries`);
}

/* ---------- Home page links ---------- */
// Plain links to every hero page inside the home page's list, so search engines can find the pages
// without running JavaScript. The page script replaces them with the hero cards.
{
  const home = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
  const countries = [...new Set(ordered.map(h => h.country))];
  const links = countries.map(c => `
      <section class="country"><h3>${esc(c)}</h3><ul>${ordered.filter(h => h.country === c).map(h =>
        `<li><a href="${heroPath(h)}">${esc(h.name)}: ${esc(h.flight)} (${h.year})</a></li>`).join("")}</ul></section>`).join("");
  const updated = home.replace(/(<!-- hero-links:[^>]*-->)[\s\S]*?(<!-- \/hero-links -->)/, `$1${links}\n    $2`);
  if (updated === home && !home.includes("<!-- hero-links:")) throw new Error('index.html is missing the "hero-links" markers inside #list.');
  // Countries on the Acts of kindness page, each linking to its stories.
  const kindCountries = [...new Set(KINDNESS.map(k => k.country))].sort();
  const kindLinks = `<nav class="k-countries" aria-label="Acts of kindness by country">${kindCountries.map(c =>
    `<a href="/${KIND_SLUG}/#k-${heroSlug({ name: c })}">${esc(c)} <span>${KINDNESS.filter(k => k.country === c).length}</span></a>`).join("")}</nav>`;
  const withKind = updated.replace(/(<!-- kindness-links:[^>]*-->)[\s\S]*?(<!-- \/kindness-links -->)/, `$1${kindLinks}$2`);
  if (write("index.html", withKind)) console.log("Home page links updated");
}

// Every page on the site, for the repeated-text check and the sitemap.
const urls = [`${SITE}/`, `${SITE}/${KIND_SLUG}/`, `${SITE}/what-passengers-can-do/`, ...ordered.map(heroUrl)];

/* ---------- No repeated text ---------- */
// Google can treat pages that share the same paragraphs as duplicates and leave some out of search.
// Stop the build if any sentence-length piece of text (60+ characters) appears on more than one page.
{
  const pages = ["index.html", ...urls.slice(1).map(u => u.slice(SITE.length + 1) + "index.html")];
  const where = new Map();
  for (const p of pages) {
    const html = fs.readFileSync(path.join(ROOT, p), "utf8")
      .replace(/<head>[\s\S]*?<\/head>|<header>[\s\S]*?<\/header>|<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/g, "");
    const blocks = html.split(/<\/?(?:p|li|h\d|summary|details|figcaption|dd|dt|div|span|a|section|td)\b[^>]*>/)
      .map(t => t.replace(/<[^>]+>/g, " ").replace(/&[a-z#0-9]+;/g, " ").replace(/\s+/g, " ").trim()).filter(t => t.length >= 60);
    for (const b of new Set(blocks)) where.set(b, [...(where.get(b) || []), p]);
  }
  const repeats = [...where].filter(([, ps]) => ps.length > 1);
  if (repeats.length) throw new Error("The same text is on more than one page:\n" +
    repeats.map(([b, ps]) => `  "${b.slice(0, 90)}…" on ${ps.join(", ")}`).join("\n"));
  console.log(`Repeated text: none across ${pages.length} pages`);
}

/* ---------- Sitemap ---------- */
const today = new Date().toISOString().slice(0, 10);
write("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>\n    <loc>${u}</loc>\n    <lastmod>${today}</lastmod>\n  </url>`).join("\n")}
</urlset>
`);
console.log(`Sitemap: ${urls.length} addresses`);

/* ---------- Share images (1200x630) ---------- */
const dataUri = p => {
  const file = path.join(ROOT, p);
  const type = path.extname(file).toLowerCase() === ".png" ? "image/png" : "image/jpeg";
  return `data:${type};base64,${fs.readFileSync(file).toString("base64")}`;
};
const CARD_CSS = `
  * { box-sizing: border-box; margin: 0; }
  body { width: 1200px; height: 630px; overflow: hidden; background: #0b1118; color: #e8eef5;
    font-family: "Segoe UI", system-ui, -apple-system, Roboto, sans-serif; display: flex; }
  .photo { width: 500px; height: 630px; flex: none; background: #182a3f center / cover no-repeat; position: relative; display: grid; place-items: center; }
  .photo::after { content: ""; position: absolute; inset: 0; background: linear-gradient(90deg, transparent 70%, #0b1118); }
  .ini { font-size: 150px; font-weight: 700; color: #8fbcf3; width: 300px; height: 300px; border-radius: 50%; border: 6px solid #e0b44c; display: grid; place-items: center; background: #131c26; }
  .text { flex: 1; padding: 56px 60px 48px 44px; display: flex; flex-direction: column; border-top: 8px solid #e0b44c; }
  .brand { display: flex; align-items: center; gap: 12px; font-size: 30px; font-weight: 700; }
  .brand svg { width: 38px; height: 38px; color: #6aa5ec; } .brand b { color: #6aa5ec; }
  .eyebrow { margin-top: auto; color: #e0b44c; font-size: 24px; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; }
  h1 { font-size: 66px; line-height: 1.05; margin: 12px 0 18px; }
  h1.long { font-size: 52px; }
  .line { font-size: 28px; color: #c5d2e0; } .stat { margin-top: 10px; font-size: 26px; color: #93a3b5; }
  .live { display: inline-block; margin-top: 18px; font-size: 22px; font-weight: 700; color: #f3a6a6; }
  .url { margin-top: auto; padding-top: 26px; font-size: 24px; color: #93a3b5; }`;

const heroCardHtml = h => `<!doctype html><html><head><meta charset="utf-8"><style>${CARD_CSS}</style></head><body>
  <div class="photo" style="${h.image ? `background-image:url(${dataUri(h.image)});background-position:${h.imageKind === "portrait" ? "50% 30%" : "center"}` : ""}">
    ${h.image ? "" : `<div class="ini">${esc(initials(h.name))}</div>`}</div>
  <div class="text">
    <div class="brand">${PLANE}<span>Air<b>Sky</b>Hero</span></div>
    <div class="eyebrow">${esc(h.role)} · ${esc(h.country)}</div>
    <h1 class="${h.name.length > 24 ? "long" : ""}">${esc(h.name)}</h1>
    <div class="line">${esc(h.flight)} · ${h.year}</div>
    <div class="stat">${h.aboard ? `${h.survived} of ${h.aboard} aboard survived` : esc(h.place)}</div>
    ${h.developing ? '<span class="live">● Developing story</span>' : ""}
    <div class="url">airskyhero.com</div>
  </div></body></html>`;

const homeCardHtml = () => {
  const pics = HEROES.filter(h => h.image && h.imageKind === "portrait").slice(0, 6);
  return `<!doctype html><html><head><meta charset="utf-8"><style>${CARD_CSS}
    .mosaic { width: 500px; height: 630px; flex: none; display: grid; grid-template-columns: 1fr 1fr; position: relative; }
    .mosaic div { background: center 30% / cover no-repeat; }
    .mosaic::after { content: ""; position: absolute; inset: 0; background: linear-gradient(90deg, rgba(11,17,24,.15) 60%, #0b1118); }
    h1 { font-size: 64px; }</style></head><body>
    <div class="mosaic">${pics.map(h => `<div style="background-image:url(${dataUri(h.image)})"></div>`).join("")}</div>
    <div class="text">
      <div class="brand">${PLANE}<span>Air<b>Sky</b>Hero</span></div>
      <div class="eyebrow">${HEROES.length} heroes · ${new Set(HEROES.map(h => h.country)).size} countries</div>
      <h1>Heroes of the sky, around the world</h1>
      <div class="line">Pilots, cabin crew and passengers whose courage saved lives.</div>
      <div class="url">airskyhero.com</div>
    </div></body></html>`;
};

const CHROME = [process.env.CHROME_PATH,
  "C:/Program Files/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/usr/bin/google-chrome", "/usr/bin/chromium"].find(p => p && fs.existsSync(p));

if (!CHROME) {
  console.warn("Share images skipped: Chrome not found (set CHROME_PATH to its location).");
} else {
  const { default: puppeteer } = await import("puppeteer-core");
  const browser = await puppeteer.launch({ executablePath: CHROME, headless: true });
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 1200, height: 630, deviceScaleFactor: 1 });
    const shoot = async (file, html) => {
      await page.setContent(html, { waitUntil: "load" });
      await page.evaluate(() => document.fonts.ready);
      return write(file, await page.screenshot({ type: "jpeg", quality: 85 }));
    };
    let n = 0;
    for (const h of ordered) if (await shoot(`share/${heroSlug(h)}.jpg`, heroCardHtml(h))) n++;
    if (await shoot("share/home.jpg", homeCardHtml())) n++;
    for (const f of fs.readdirSync(path.join(ROOT, "share"))) {
      if (f !== "home.jpg" && !slugs.has(f.replace(/\.jpg$/, ""))) fs.rmSync(path.join(ROOT, "share", f));
    }
    console.log(`Share images: ${ordered.length + 1} (${n} updated)`);
  } finally {
    await browser.close();
  }
}
