// Builds the parts of the site that come from heroes.js. Run with: npm run build
//   <slug>/index.html   one page per hero (airskyhero.com/smit-machchhar/), readable by Google
//   share/<slug>.jpg     1200x630 preview image shown when a hero's link is shared
//   share/home.jpg       preview image for the home page
//   sitemap.xml          every page, for Google Search Console
// Preview images need Google Chrome (or set CHROME_PATH); pages and sitemap are written either way.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const HEROES = require(path.join(ROOT, "heroes.js"));
const HELPERS = require(path.join(ROOT, "helpers.js"));
const KINDNESS = require(path.join(ROOT, "kindness.js"));
const KIND_SLUG = "acts-of-kindness";
const FACTS = require(path.join(ROOT, "facts.js"));
const FACTS_SLUG = "fun-facts";
const { SITE, esc, youtubeId, newsDate, uniqueStories, heroSlug, heroPath, heroUrl, shareImage, newsHtml, helpersHtml, developingText, shareHtml, splitNews } = require(path.join(ROOT, "news.js"));

const MARK = `<!-- Generated by scripts/build.mjs from heroes.js. Edit heroes.js, then run "npm run build". -->`;
const abs = p => (p && !/^https?:/.test(p) ? "/" + p.replace(/^\//, "") : p);
const initials = name => name.replace(/["(].*?[")]/g, "").split(/\s+/).filter(w => /^[A-Z]/.test(w)).map(w => w[0]).slice(0, 2).join("");
const clip = (s, n) => (s.length <= n ? s : s.slice(0, s.lastIndexOf(" ", n - 1)) + "…");
const write = (file, data) => {
  const full = path.join(ROOT, file);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  if (fs.existsSync(full) && Buffer.compare(fs.readFileSync(full), Buffer.from(data)) === 0) return false;
  fs.writeFileSync(full, data);
  return true;
};

// Same order as the home page list: by country, then year.
const ordered = [...HEROES].sort((a, b) => a.country.localeCompare(b.country) || a.year - b.year);
const slugs = new Set();
for (const h of ordered) {
  const s = heroSlug(h);
  if (s === KIND_SLUG || s === FACTS_SLUG) throw new Error(`"${s}" is a section page. Give this hero another slug in heroes.js.`);
  if (slugs.has(s)) throw new Error(`Two heroes have the page address "${s}". Give one of them slug: "..." in heroes.js.`);
  slugs.add(s);
}

// Every news link belongs on one hero's page only, so no two pages list the same story.
{
  const seen = new Map();
  for (const h of HEROES) for (const n of h.news || []) {
    if (seen.has(n.url)) throw new Error(`"${n.url}" is in the news of both ${seen.get(n.url)} and ${h.name}. Keep it on one of them in heroes.js.`);
    seen.set(n.url, h.name);
  }
}

/* ---------- Hero pages ---------- */
const PLANE = `<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M21 16v-2l-8-5V3.5a1.5 1.5 0 0 0-3 0V9l-8 5v2l8-2.5V19l-2 1.5V22l3.5-1 3.5 1v-1.5L13 19v-5.5l8 2.5z"/></svg>`;

// Fonts, theme colour and the light/dark switch, added to the <head> of every page.
const THEME_COLOR = "#0b1118";
const HEAD_LINKS = `<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/site.css">
<script src="/theme.js"></script>`;

// Header shared by every page: logo, a ticker of the newest news headlines, search and theme buttons,
// then the row of round section buttons. "active" is the section button marked as the current page.
const icon = d => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${d}</svg>`;
const ICONS = {
  latest: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  map: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/>',
  heroes: '<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1 6.2L12 17.3l-5.5 2.9 1-6.2L3 9.6l6.2-.9z"/>',
  pilots: '<path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z"/>',
  crew: '<circle cx="9" cy="8" r="3.5"/><path d="M2.5 20a6.5 6.5 0 0 1 13 0M16 4.5a3.5 3.5 0 0 1 0 7M21.5 20a6.5 6.5 0 0 0-4-6"/>',
  passengers: '<path d="M8 10V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v5M7 18v-6a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v6M5 18h14M7 18v3M17 18v3"/>',
  kindness: '<path d="M19 14c1.5-1.5 3-3.2 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.8 0-3 .5-4.5 2-1.5-1.5-2.7-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4 3 5.5l7 7z"/>',
  facts: '<path d="M9 18h6M10 21h4M12 3a6 6 0 0 0-3.5 10.9c.6.5 1 1.2 1 2.1h5c0-.9.4-1.6 1-2.1A6 6 0 0 0 12 3z"/>',
  safety: '<path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6z"/><path d="m9 12 2 2 4-4"/>',
  about: '<circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/>'
};
const SECTIONS = [
  ["latest", "Latest", "/"],
  ["map", "Map", "/#map-section"],
  ["heroes", "Heroes", "/#heroes"],
  ["pilots", "Pilots", "/?role=Pilot#heroes"],
  ["crew", "Cabin crew", "/?role=Cabin+crew#heroes"],
  ["passengers", "Passengers", "/?role=Passenger#heroes"],
  ["kindness", "Kindness", "/acts-of-kindness/"],
  ["facts", "Fun facts", "/fun-facts/"],
  ["safety", "Safety", "/what-passengers-can-do/"],
  ["about", "About", "/#about"]
];
// The newest dated news about any hero, main stories (top: true) first on the same day, each story once.
const tickerItems = uniqueStories(HEROES.flatMap(h => (h.news || []).filter(n => n.date && n.title))
  .sort((a, b) => b.date.localeCompare(a.date) || !!b.top - !!a.top)).slice(0, 8)
  .map(n => `<li><a href="${esc(n.url)}" target="_blank" rel="noopener"><span class="t-date">${esc(newsDate(n.date))}</span>${esc(n.title)}</a></li>`).join("");
const header = active => `<!-- site-header: written by scripts/build.mjs -->
<header>
  <div class="wrap top">
    <a class="logo" href="/" aria-label="AirSkyHero home">${PLANE}<span>AirSky<b>Hero</b></span></a>
    <span class="t-label" aria-hidden="true">Latest</span>
    <div class="ticker" aria-label="Latest headlines">
      <div class="ticker-track"><ul>${tickerItems}</ul><ul aria-hidden="true" inert>${tickerItems}</ul></div>
    </div>
    <div class="tools">
      <a class="ic-btn" id="search-btn" href="/#heroes" aria-label="Search heroes">${icon('<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>')}</a>
      <button class="ic-btn" id="theme-btn" type="button" aria-label="Switch between light and dark">${icon('<path class="moon" d="M20 14.5A8 8 0 0 1 9.5 4 8 8 0 1 0 20 14.5z"/><g class="sun"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></g>')}</button>
    </div>
  </div>
</header>
<nav class="cats" aria-label="Sections">
  <div class="wrap cats-row">${SECTIONS.map(([key, label, href]) =>
    `<a class="cat" href="${href}"${key === active ? ' aria-current="page"' : ""}><span class="cat-ic">${icon(ICONS[key])}</span>${label}</a>`).join("")}</div>
</nav>
<!-- /site-header -->`;

// Pages not generated here (home and the safety guide) get the same header and <head> links.
for (const [file, active] of [["index.html", "latest"], ["what-passengers-can-do/index.html", "safety"]]) {
  const html = fs.readFileSync(path.join(ROOT, file), "utf8");
  const updated = html
    .replace(/(?:<!-- site-header:[^>]*-->[\s\S]*?<!-- \/site-header -->|<header>[\s\S]*?<\/header>)/, header(active))
    .replace(/(?:<link rel="preconnect"[^>]*>\n)*(?:<link href="https:\/\/fonts[^>]*>\n)?<link rel="stylesheet" href="\/site.css">(?:\n<script src="\/theme.js"><\/script>)?/, HEAD_LINKS)
    .replace(/<meta name="theme-color" content="[^"]*">/, `<meta name="theme-color" content="${THEME_COLOR}">`);
  if (write(file, updated)) console.log(`${file}: header updated`);
}

const heroCard = h => `
        <a class="card" href="${heroPath(h)}">
          <div class="thumb">${h.image
            ? `<img src="${esc(abs(h.image))}" alt="${esc(h.imageAlt || "")}" class="${h.imageKind === "portrait" ? "face" : ""}" loading="lazy" width="640" height="360">`
            : `<span class="initials" aria-hidden="true">${esc(initials(h.name))}</span>`}</div>
          <h4>${esc(h.name)}</h4>
          <div class="tags"><span class="tag">${esc(h.role)}</span><span class="tag">${h.year}</span></div>
          <p class="flight">${esc(h.flight)}</p>
          <span class="more">Read story →</span>
        </a>`;

// Other heroes from the same flight first, then the same country, then the closest in time.
function related(h) {
  const rank = o => (o.flight === h.flight ? 0 : o.country === h.country ? 1 : 2) * 1e4 + Math.abs(o.year - h.year);
  return HEROES.filter(o => o !== h).sort((a, b) => rank(a) - rank(b)).slice(0, 3);
}

// Optional sections from heroes.js: timeline (dated events with numbered source links) and faq (questions and answers).
const srcLinks = urls => (urls || []).length ? ` <span class="h-src">Sources: ${urls.map((u, i) =>
  `<a href="${esc(u)}" target="_blank" rel="noopener" title="${esc(u.replace(/^https?:\/\/(www\.)?/, "").split("/")[0])}">${i + 1}</a>`).join(" ")}</span>` : "";
const timelineHtml = h => !h.timeline ? "" : `    <h2 class="hp-h">Timeline</h2>
    <ol class="timeline">
${h.timeline.map(t => `      <li><span class="tl-date">${esc(t.date)}</span><span class="tl-text">${esc(t.text)}${srcLinks(t.sources)}</span></li>`).join("\n")}
    </ol>
`;
const faqHtml = h => !h.faq ? "" : `    <h2 class="hp-h">Questions people ask</h2>
    <div class="faq">
${h.faq.map(f => `      <details><summary>${esc(f.q)}</summary><p>${esc(f.a)}${srcLinks(f.sources)}</p></details>`).join("\n")}
    </div>
`;

function heroPage(h, i) {
  const title = `${h.seoTitle || `${h.name}: ${h.flight} (${h.year})`} | AirSkyHero`;
  const description = h.seoDescription || clip(h.story, 158);
  const prev = ordered[i - 1], next = ordered[i + 1];
  const facts = [
    ["Flight", h.flight], ["Date", h.date], ["Aircraft", h.aircraft], ["Location", h.place],
    ...(h.aboard ? [["Survivors", `${h.survived} of ${h.aboard} aboard`]] : [])
  ];
  // Google needs uploadDate and thumbnailUrl on every VideoObject, so a video without a date is left out of the markup.
  const videos = splitNews(h).videos.filter(v => v.date || console.warn(`${h.name}: video ${v.url} has no date, so it is left out of the structured data.`));
  const videoLd = v => {
    const id = youtubeId(v.url), name = v.title || v.outlet;
    return {
      "@type": "VideoObject", name, description: v.outlet ? `${name}. Video from ${v.outlet}.` : name,
      thumbnailUrl: `https://i.ytimg.com/vi/${id}/hqdefault.jpg`, uploadDate: v.date,
      contentUrl: `https://www.youtube.com/watch?v=${id}`, embedUrl: `https://www.youtube.com/embed/${id}`
    };
  };
  const ld = {
    "@context": "https://schema.org", "@type": "Article",
    headline: `${h.name}: ${h.flight}`, description, url: heroUrl(h), image: shareImage(h),
    about: { "@type": h.role === "Passenger" && /^Passengers/.test(h.name) ? "Thing" : "Person", name: h.name, nationality: h.country },
    publisher: { "@type": "Organization", name: "AirSkyHero", url: SITE },
    ...(videos.length ? { video: videos.map(videoLd) } : {})
  };
  const faqLd = h.faq && {
    "@context": "https://schema.org", "@type": "FAQPage",
    mainEntity: h.faq.map(f => ({ "@type": "Question", name: f.q, acceptedAnswer: { "@type": "Answer", text: f.a } }))
  };
  return `<!doctype html>
${MARK}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<meta name="theme-color" content="${THEME_COLOR}">
<link rel="canonical" href="${heroUrl(h)}">
<meta property="og:type" content="article">
<meta property="og:site_name" content="AirSkyHero">
<meta property="og:title" content="${esc(`${h.name}: ${h.flight}`)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${heroUrl(h)}">
<meta property="og:image" content="${shareImage(h)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${esc(`${h.name}, ${h.role}, ${h.flight}`)}">
<meta name="twitter:card" content="summary_large_image">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
${HEAD_LINKS}
<script type="application/ld+json">${JSON.stringify(ld).replace(/</g, "\\u003c")}</script>
${faqLd ? `<script type="application/ld+json">${JSON.stringify(faqLd).replace(/</g, "\\u003c")}</script>\n` : ""}</head>
<body>

${header("heroes")}

<main class="wrap hero-page">
  <p class="crumbs"><a href="/">Home</a> › <a href="/#heroes">Heroes</a> › ${esc(h.country)}</p>
  <article>
    <div class="hp-head">
      <p class="eyebrow">${esc(h.role)} · ${esc(h.country)}</p>
      <h1>${esc(h.name)}</h1>
      <div class="tags"><span class="tag">${esc(h.flight)}</span><span class="tag">${h.year}</span>${h.developing ? '<span class="badge-live">Developing story</span>' : ""}</div>
    </div>
${h.image ? `    <figure class="hp-photo">
      <img src="${esc(abs(h.image))}" alt="${esc(h.imageAlt || "")}">
${h.imageCredit ? `      <figcaption>Photo: <a href="${esc(h.imageCreditUrl || "")}" target="_blank" rel="noopener">${esc(h.imageCredit)}</a></figcaption>\n` : ""}    </figure>
` : ""}    <dl class="facts">
${facts.map(([k, v]) => `      <div class="fact"><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join("\n")}
    </dl>
${h.developing ? `    <p class="developing">${esc(developingText(h))}</p>\n` : ""}    <p class="hp-story">${esc(h.story)}</p>
${timelineHtml(h)}${helpersHtml(h, HELPERS, HEROES).replace(/^\n/, "")}${HELPERS[h.flight] ? "\n" : ""}${faqHtml(h)}    <p class="hp-source">Source: <a href="${esc(h.source)}" target="_blank" rel="noopener">${esc(h.source.replace(/^https?:\/\/(www\.)?/, ""))} ↗</a></p>
    <p class="hp-guide">If something goes wrong on your flight: <a href="/what-passengers-can-do/">what passengers can do, close by or farther away →</a></p>
    ${shareHtml(h)}
    <section class="news" aria-labelledby="d-news-h">${newsHtml(h)}
    </section>
  </article>

  <section class="hp-more" aria-labelledby="more-h">
    <h2 id="more-h">More heroes</h2>
    <div class="grid">${related(h).map(heroCard).join("")}
    </div>
    <nav class="hp-pager" aria-label="Previous and next hero">
      <span>${prev ? `<a href="${heroPath(prev)}">← ${esc(prev.name)}</a>` : ""}</span>
      <span>${next ? `<a href="${heroPath(next)}">${esc(next.name)} →</a>` : ""}</span>
    </nav>
    <a class="hp-home" href="/#heroes">See all heroes on the world map →</a>
  </section>
</main>

<script src="/news.js"></script>
<script data-goatcounter="https://airskyhero.goatcounter.com/count" async src="https://gc.zgo.at/count.js"></script>
<script>
if ("serviceWorker" in navigator && location.protocol === "https:") navigator.serviceWorker.register("/sw.js");
</script>
</body>
</html>
`;
}

let changed = 0;
ordered.forEach((h, i) => { if (write(`${heroSlug(h)}/index.html`, heroPage(h, i))) changed++; });

// Remove pages of heroes that were deleted or renamed (only folders this script made).
for (const d of fs.readdirSync(ROOT, { withFileTypes: true })) {
  const page = path.join(ROOT, d.name, "index.html");
  if (d.isDirectory() && !slugs.has(d.name) && d.name !== KIND_SLUG && d.name !== FACTS_SLUG && fs.existsSync(page) && fs.readFileSync(page, "utf8").includes(MARK)) {
    fs.rmSync(path.join(ROOT, d.name), { recursive: true });
    console.log(`Removed old page /${d.name}/`);
  }
}
console.log(`Hero pages: ${ordered.length} (${changed} updated)`);

/* ---------- Acts of kindness page ---------- */
// World map on the page, drawn in the browser like the home page map. Clicking a country jumps to its stories.
const KIND_MAP_JS = `// Our country names -> names used by the world-atlas map data.
const MAP_NAME = { "United States": "United States of America" };
const NUDGE = { "United States": [-98, 39], "Canada": [-100, 57] };
function pick(c) {
  document.querySelectorAll("#map .land.has").forEach(p => p.classList.toggle("selected", p.dataset.c === c));
  location.hash = KIND[c].id;
}
addEventListener("DOMContentLoaded", async () => {
  const status = document.getElementById("map-status"), tip = document.getElementById("tip");
  try {
    const world = await d3.json("https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json");
    const features = topojson.feature(world, world.objects.countries).features;
    const ours = Object.fromEntries(Object.keys(KIND).map(c => [MAP_NAME[c] || c, c]));
    const projection = d3.geoNaturalEarth1().fitExtent([[8, 8], [952, 492]], { type: "Sphere" });
    const path = d3.geoPath(projection);
    const svg = d3.select("#map");
    svg.append("path").attr("class", "sphere").attr("d", path({ type: "Sphere" }));
    svg.append("path").attr("class", "grat").attr("d", path(d3.geoGraticule10()));
    const label = c => c + " · " + KIND[c].n + (KIND[c].n === 1 ? " story" : " stories");
    svg.append("g").selectAll("path").data(features).join("path")
      .attr("d", path)
      .attr("class", d => "land" + (ours[d.properties.name] ? " has" : ""))
      .attr("data-c", d => ours[d.properties.name] || null)
      .attr("tabindex", d => ours[d.properties.name] ? 0 : null)
      .attr("role", d => ours[d.properties.name] ? "button" : null)
      .attr("aria-label", d => ours[d.properties.name] ? label(ours[d.properties.name]) : null)
      .filter(d => ours[d.properties.name])
      .on("click", (e, d) => pick(ours[d.properties.name]))
      .on("keydown", (e, d) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); pick(ours[d.properties.name]); } })
      .on("mousemove", (e, d) => {
        const box = document.getElementById("map").parentElement.getBoundingClientRect();
        tip.textContent = label(ours[d.properties.name]);
        tip.style.left = (e.clientX - box.left + 12) + "px";
        tip.style.top = (e.clientY - box.top + 12) + "px";
        tip.style.opacity = 1;
      })
      .on("mouseleave", () => { tip.style.opacity = 0; });
    svg.append("g").selectAll("text")
      .data(features.filter(d => ours[d.properties.name]))
      .join("text").attr("class", "pin")
      .attr("transform", d => {
        const c = ours[d.properties.name];
        const [x, y] = NUDGE[c] ? projection(NUDGE[c]) : path.centroid(d);
        return "translate(" + x + "," + (y + 4) + ")";
      })
      .text(d => KIND[ours[d.properties.name]].n);
    status.remove();
  } catch (err) {
    status.className = "map-error";
    status.textContent = "The map couldn't load. Use the country buttons below instead.";
  }
});`;

// airskyhero.com/acts-of-kindness/: stories from kindness.js, grouped by country.
{
  const ids = new Set();
  for (const k of KINDNESS) {
    if (ids.has(k.id)) throw new Error(`Two kindness stories have the id "${k.id}" in kindness.js.`);
    ids.add(k.id);
    if ((k.sources || []).length < 3) throw new Error(`Kindness story "${k.id}" needs at least three sources in kindness.js.`);
  }
  const countries = [...new Set(KINDNESS.map(k => k.country))].sort();
  const cid = c => "k-" + heroSlug({ name: c });
  const story = k => `
        <li class="k-card" id="${esc(k.id)}">
          <h3>${esc(k.title)}</h3>
          <p class="k-meta">${[k.who, k.airline, k.flight, k.date].filter(Boolean).map(esc).join(" · ")}</p>
          <p>${esc(k.summary)}${srcLinks(k.sources)}</p>
        </li>`;
  const title = "Acts of kindness on aeroplanes, country by country";
  const description = `${KINDNESS.length} true stories of crew and passengers looking after strangers on flights, from ${countries.length} countries, each checked against at least three sources.`;
  const ld = {
    "@context": "https://schema.org", "@type": "CollectionPage", name: title, description, url: `${SITE}/${KIND_SLUG}/`,
    publisher: { "@type": "Organization", name: "AirSkyHero", url: SITE }
  };
  const page = `<!doctype html>
${MARK}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)} | AirSkyHero</title>
<meta name="description" content="${esc(description)}">
<meta name="theme-color" content="${THEME_COLOR}">
<link rel="canonical" href="${SITE}/${KIND_SLUG}/">
<meta property="og:type" content="article">
<meta property="og:site_name" content="AirSkyHero">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${SITE}/${KIND_SLUG}/">
<meta property="og:image" content="${SITE}/share/home.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
${HEAD_LINKS}
<script type="application/ld+json">${JSON.stringify(ld).replace(/</g, "\\u003c")}</script>
</head>
<body>

${header("kindness")}

<main class="wrap hero-page guide kindness">
  <p class="crumbs"><a href="/">Home</a> › Acts of kindness</p>
  <article>
    <div class="hp-head">
      <p class="eyebrow">Acts of kindness</p>
      <h1>Kindness at 35,000 feet</h1>
    </div>
    <p class="hp-story">Not every hero of the sky lands a broken plane. These are true stories of cabin crew, pilots, passengers and whole towns who looked after strangers on a flight. Every story is checked against at least three independent sources, linked under it.</p>
    <div class="map-box">
      <svg id="map" viewBox="0 0 960 500" role="img" aria-label="World map of acts of kindness by country"></svg>
      <div class="map-loading" id="map-status">Loading map…</div>
      <div class="tooltip" id="tip" aria-hidden="true"></div>
    </div>
    <nav class="k-countries" aria-label="Countries">${countries.map(c =>
      `<a href="#${cid(c)}">${esc(c)} <span>${KINDNESS.filter(k => k.country === c).length}</span></a>`).join("")}</nav>
${countries.map(c => `    <section aria-labelledby="${cid(c)}">
      <h2 id="${cid(c)}">${esc(c)}</h2>
      <ul class="k-list">${KINDNESS.filter(k => k.country === c).sort((a, b) => a.year - b.year).map(story).join("")}
      </ul>
    </section>`).join("\n")}
  </article>
  <a class="hp-home" href="/#heroes">See the heroes of the sky →</a>
</main>

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.9.0/d3.min.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/topojson/3.0.2/topojson.min.js" defer></script>
<script data-goatcounter="https://airskyhero.goatcounter.com/count" async src="https://gc.zgo.at/count.js"></script>
<script>
const KIND = ${JSON.stringify(Object.fromEntries(countries.map(c => [c, { n: KINDNESS.filter(k => k.country === c).length, id: cid(c) }])))};
${KIND_MAP_JS}
if ("serviceWorker" in navigator && location.protocol === "https:") navigator.serviceWorker.register("/sw.js");
</script>
</body>
</html>
`;
  if (write(`${KIND_SLUG}/index.html`, page)) console.log("Acts of kindness page updated");
  console.log(`Acts of kindness: ${KINDNESS.length} stories from ${countries.length} countries`);
}

/* ---------- Fun facts page ---------- */
// airskyhero.com/fun-facts/: facts from facts.js, grouped by topic in the order topics first appear there.
const factTopics = [...new Set(FACTS.map(f => f.topic))];
const topicId = t => "f-" + heroSlug({ name: t });
{
  const ids = new Set();
  for (const f of FACTS) {
    if (ids.has(f.id)) throw new Error(`Two fun facts have the id "${f.id}" in facts.js.`);
    ids.add(f.id);
    if ((f.sources || []).length < 3) throw new Error(`Fun fact "${f.id}" needs at least three sources in facts.js.`);
  }
  // Each topic gets an icon and one of four colours (t0 to t3 in site.css), in the order the topics appear.
  const TOPIC_ICONS = {
    "Life on board": ICONS.passengers,
    "Food and drink": '<path d="M5 8h12v4a6 6 0 0 1-6 6h0a6 6 0 0 1-6-6zM17 9h1.5a2.5 2.5 0 0 1 0 5H16.5M8 2.5v2.5M11 2.5v2.5M14 2.5v2.5M4 21h14"/>',
    "How planes work": '<circle cx="12" cy="12" r="3"/><path d="M12 2.5v3M12 18.5v3M2.5 12h3M18.5 12h3M5.3 5.3l2.1 2.1M16.6 16.6l2.1 2.1M5.3 18.7l2.1-2.1M16.6 7.4l2.1-2.1"/>',
    "Firsts and record breakers": '<path d="M8 21h8M12 17v4M7 4h10v5a5 5 0 0 1-10 0zM7 6H4.5a3 3 0 0 0 3 4.5M17 6h2.5a3 3 0 0 1-3 4.5"/>'
  };
  const topicIcon = t => icon(TOPIC_ICONS[t] || ICONS.facts);
  const topicClass = t => "t" + (factTopics.indexOf(t) % 4);
  const shown = factTopics.flatMap(t => FACTS.filter(f => f.topic === t));
  const SHARE = icon('<circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.6-4.4M8.2 13.2l7.6 4.4"/>');
  const fact = f => `
        <li class="fc" id="${esc(f.id)}">
          <div class="fc-top"><span class="fc-no">No. ${String(shown.indexOf(f) + 1).padStart(2, "0")}</span><span class="fc-ic">${topicIcon(f.topic)}</span></div>
${f.stat ? `          <p class="fc-stat"><b>${esc(f.stat)}</b><span>${esc(f.statLabel || "")}</span></p>\n` : ""}          <h3>${esc(f.title)}</h3>
${f.when ? `          <p class="fc-when">${esc(f.when)}</p>\n` : ""}          <p class="fc-text">${esc(f.summary)}</p>
          <div class="fc-foot">${srcLinks(f.sources).trim()}<button class="fc-share" type="button" data-id="${esc(f.id)}" data-title="${esc(f.title)}">${SHARE}<span>Share</span></button></div>
        </li>`;
  const sourceCount = new Set(FACTS.flatMap(f => f.sources)).size;
  // Banner art: a dashed flight path with a plane at the end and a couple of clouds.
  const FLIGHT_ART = `<svg class="ff-art" viewBox="0 0 400 220" aria-hidden="true">
      <path class="ff-cloud" d="M250 170a18 18 0 0 1 34-8 14 14 0 0 1 24 10 11 11 0 0 1 0 22h-56a12 12 0 0 1-2-24z"/>
      <path class="ff-cloud" d="M60 70a14 14 0 0 1 26-6 11 11 0 0 1 19 8 9 9 0 0 1 0 17H62a10 10 0 0 1-2-19z"/>
      <path class="ff-path" d="M20 200C110 190 170 120 240 90s90-40 120-70"/>
      <g transform="translate(360 22) rotate(56)"><path class="ff-plane" d="M0-20c2 0 3 2 3 5v9l15 9v4L3 2v9l5 4v3l-8-2-8 2v-3l5-4V2l-15 5V3l15-9v-9c0-3 1-5 3-5z"/></g>
    </svg>`;
  const title = "Fun facts about planes and flying";
  const description = `${FACTS.length} surprising true facts about airliners and air travel, from piano bars on jumbo jets to ashtrays on non-smoking flights, each checked against at least three sources.`;
  const ld = {
    "@context": "https://schema.org", "@type": "CollectionPage", name: title, description, url: `${SITE}/${FACTS_SLUG}/`,
    publisher: { "@type": "Organization", name: "AirSkyHero", url: SITE }
  };
  const page = `<!doctype html>
${MARK}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(title)} | AirSkyHero</title>
<meta name="description" content="${esc(description)}">
<meta name="theme-color" content="${THEME_COLOR}">
<link rel="canonical" href="${SITE}/${FACTS_SLUG}/">
<meta property="og:type" content="article">
<meta property="og:site_name" content="AirSkyHero">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${SITE}/${FACTS_SLUG}/">
<meta property="og:image" content="${SITE}/share/home.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta name="twitter:card" content="summary_large_image">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
${HEAD_LINKS}
<script type="application/ld+json">${JSON.stringify(ld).replace(/</g, "\\u003c")}</script>
</head>
<body>

${header("facts")}

<main class="wrap facts-page">
  <p class="crumbs"><a href="/">Home</a> › Fun facts</p>
  <article>
    <div class="ff-hero">
      ${FLIGHT_ART}
      <p class="eyebrow">Fun facts</p>
      <h1>Did you know?</h1>
      <p class="ff-lead">Jumbo jets once had piano bars, and brand-new planes still come with ashtrays. Here are some of the stranger true stories behind the planes we fly on. Every fact is checked against at least three independent sources, linked under it.</p>
      <div class="ff-nums"><span><b>${FACTS.length}</b> facts</span><span><b>${factTopics.length}</b> topics</span><span><b>${sourceCount}</b> sources</span></div>
      <button class="ff-surprise" id="surprise" type="button" hidden>${icon(ICONS.pilots)}Surprise me</button>
    </div>
    <nav class="ff-topics" aria-label="Topics">${factTopics.map(t =>
      `<a class="${topicClass(t)}" href="#${topicId(t)}">${topicIcon(t)}${esc(t)} <span>${FACTS.filter(f => f.topic === t).length}</span></a>`).join("")}</nav>
${factTopics.map(t => `    <section class="ff-sec ${topicClass(t)}" aria-labelledby="${topicId(t)}">
      <h2 id="${topicId(t)}"><span class="ff-sec-ic">${topicIcon(t)}</span>${esc(t)}</h2>
      <ul class="ff-grid">${FACTS.filter(f => f.topic === t).map(fact).join("")}
      </ul>
    </section>`).join("\n")}
  </article>
  <a class="hp-home" href="/#heroes">See the heroes of the sky →</a>
</main>

<script data-goatcounter="https://airskyhero.goatcounter.com/count" async src="https://gc.zgo.at/count.js"></script>
<script>
const cards = [...document.querySelectorAll(".fc")];
const calm = matchMedia("(prefers-reduced-motion: reduce)").matches;
// Cards fade in as they scroll into view.
if ("IntersectionObserver" in window && !calm) {
  document.documentElement.classList.add("ff-js");
  const seen = new IntersectionObserver(es => es.forEach(e => {
    if (e.isIntersecting) { e.target.classList.add("in"); seen.unobserve(e.target); }
  }), { rootMargin: "0px 0px -40px 0px" });
  cards.forEach(c => seen.observe(c));
}
// Surprise me: jump to a random fact and make it glow.
let last;
const surprise = document.getElementById("surprise");
surprise.hidden = false;
surprise.addEventListener("click", () => {
  let card;
  do card = cards[Math.floor(Math.random() * cards.length)]; while (cards.length > 1 && card === last);
  last = card;
  card.classList.add("in");
  card.scrollIntoView({ behavior: calm ? "auto" : "smooth", block: "center" });
  history.replaceState(null, "", "#" + card.id);
  card.classList.remove("flash"); void card.offsetWidth; card.classList.add("flash");
});
// Share a link to one fact: the phone's share sheet where there is one, otherwise copy the link.
document.addEventListener("click", async e => {
  const b = e.target.closest(".fc-share");
  if (!b) return;
  const url = location.origin + location.pathname + "#" + b.dataset.id, label = b.querySelector("span");
  try {
    if (navigator.share) await navigator.share({ title: b.dataset.title, url });
    else { await navigator.clipboard.writeText(url); label.textContent = "Link copied"; setTimeout(() => label.textContent = "Share", 2000); }
  } catch (err) {}
});
// Mark the topic chip of the section being read.
const chips = document.querySelectorAll(".ff-topics a");
if ("IntersectionObserver" in window) {
  const io = new IntersectionObserver(es => es.forEach(e => {
    if (e.isIntersecting) chips.forEach(a => a.classList.toggle("on", a.hash === "#" + e.target.querySelector("h2").id));
  }), { rootMargin: "-40% 0px -55% 0px" });
  document.querySelectorAll(".ff-sec").forEach(s => io.observe(s));
}
if ("serviceWorker" in navigator && location.protocol === "https:") navigator.serviceWorker.register("/sw.js");
</script>
</body>
</html>
`;
  if (write(`${FACTS_SLUG}/index.html`, page)) console.log("Fun facts page updated");
  console.log(`Fun facts: ${FACTS.length} facts in ${factTopics.length} topics`);
}

/* ---------- Home page links ---------- */
// Plain links to every hero page inside the home page's list, so search engines can find the pages
// without running JavaScript. The page script replaces them with the hero cards.
{
  const home = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
  const countries = [...new Set(ordered.map(h => h.country))];
  const links = countries.map(c => `
      <section class="country"><h3>${esc(c)}</h3><ul>${ordered.filter(h => h.country === c).map(h =>
        `<li><a href="${heroPath(h)}">${esc(h.name)}: ${esc(h.flight)} (${h.year})</a></li>`).join("")}</ul></section>`).join("");
  const updated = home.replace(/(<!-- hero-links:[^>]*-->)[\s\S]*?(<!-- \/hero-links -->)/, `$1${links}\n    $2`);
  if (updated === home && !home.includes("<!-- hero-links:")) throw new Error('index.html is missing the "hero-links" markers inside #list.');
  // Countries on the Acts of kindness page, each linking to its stories.
  const kindCountries = [...new Set(KINDNESS.map(k => k.country))].sort();
  const kindLinks = `<nav class="k-countries" aria-label="Acts of kindness by country">${kindCountries.map(c =>
    `<a href="/${KIND_SLUG}/#k-${heroSlug({ name: c })}">${esc(c)} <span>${KINDNESS.filter(k => k.country === c).length}</span></a>`).join("")}</nav>`;
  const withKindOnly = updated.replace(/(<!-- kindness-links:[^>]*-->)[\s\S]*?(<!-- \/kindness-links -->)/, `$1${kindLinks}$2`);
  // A few fun-fact headlines, each linking to the fact on the Fun facts page.
  const factLinks = `<ul class="fact-links">${FACTS.filter(f => f.home).map(f =>
    `<li><a href="/${FACTS_SLUG}/#${esc(f.id)}">${esc(f.title)}</a></li>`).join("")}</ul>`;
  const withKind = withKindOnly.replace(/(<!-- fact-links:[^>]*-->)[\s\S]*?(<!-- \/fact-links -->)/, `$1${factLinks}$2`);
  if (!withKind.includes("<!-- fact-links:")) throw new Error('index.html is missing the "fact-links" markers in the Fun facts section.');
  // When the news last changed, shown as "Updated ... ago" on the home page. The time only moves when the news does,
  // so rebuilding without new stories keeps the old time.
  const newsHash = createHash("sha1").update(JSON.stringify(HEROES.map(h => h.news || []))).digest("hex").slice(0, 12);
  const stamp = withKind.match(/<!-- news-updated:(\w+) -->[\s\S]*?datetime="([^"]+)"/);
  if (!stamp) throw new Error('index.html is missing the "news-updated" markers in the Latest heading.');
  const when = stamp[1] === newsHash ? stamp[2] : new Date().toISOString();
  const withTime = withKind.replace(/<!-- news-updated:\w+ -->[\s\S]*?<!-- \/news-updated -->/,
    `<!-- news-updated:${newsHash} --><time id="updated" datetime="${when}">${when.slice(0, 10)}</time><!-- /news-updated -->`);
  if (write("index.html", withTime)) console.log("Home page links updated");
}

// Every page on the site, for the repeated-text check and the sitemap.
const urls = [`${SITE}/`, `${SITE}/${KIND_SLUG}/`, `${SITE}/${FACTS_SLUG}/`, `${SITE}/what-passengers-can-do/`, ...ordered.map(heroUrl)];

/* ---------- No repeated text ---------- */
// Google can treat pages that share the same paragraphs as duplicates and leave some out of search.
// Stop the build if any sentence-length piece of text (60+ characters) appears on more than one page.
{
  const pages = ["index.html", ...urls.slice(1).map(u => u.slice(SITE.length + 1) + "index.html")];
  const where = new Map();
  for (const p of pages) {
    const html = fs.readFileSync(path.join(ROOT, p), "utf8")
      .replace(/<head>[\s\S]*?<\/head>|<header>[\s\S]*?<\/header>|<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/g, "");
    const blocks = html.split(/<\/?(?:p|li|h\d|summary|details|figcaption|dd|dt|div|span|a|section|td)\b[^>]*>/)
      .map(t => t.replace(/<[^>]+>/g, " ").replace(/&[a-z#0-9]+;/g, " ").replace(/\s+/g, " ").trim()).filter(t => t.length >= 60);
    for (const b of new Set(blocks)) where.set(b, [...(where.get(b) || []), p]);
  }
  const repeats = [...where].filter(([, ps]) => ps.length > 1);
  if (repeats.length) throw new Error("The same text is on more than one page:\n" +
    repeats.map(([b, ps]) => `  "${b.slice(0, 90)}…" on ${ps.join(", ")}`).join("\n"));
  console.log(`Repeated text: none across ${pages.length} pages`);
}

/* ---------- Sitemap ---------- */
const today = new Date().toISOString().slice(0, 10);
write("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>\n    <loc>${u}</loc>\n    <lastmod>${today}</lastmod>\n  </url>`).join("\n")}
</urlset>
`);
console.log(`Sitemap: ${urls.length} addresses`);

/* ---------- Share images (1200x630) ---------- */
const dataUri = p => {
  const file = path.join(ROOT, p);
  const type = path.extname(file).toLowerCase() === ".png" ? "image/png" : "image/jpeg";
  return `data:${type};base64,${fs.readFileSync(file).toString("base64")}`;
};
const CARD_CSS = `
  * { box-sizing: border-box; margin: 0; }
  body { width: 1200px; height: 630px; overflow: hidden; background: #0b1118; color: #e8eef5;
    font-family: "Segoe UI", system-ui, -apple-system, Roboto, sans-serif; display: flex; }
  .photo { width: 500px; height: 630px; flex: none; background: #182a3f center / cover no-repeat; position: relative; display: grid; place-items: center; }
  .photo::after { content: ""; position: absolute; inset: 0; background: linear-gradient(90deg, transparent 70%, #0b1118); }
  .ini { font-size: 150px; font-weight: 700; color: #8fbcf3; width: 300px; height: 300px; border-radius: 50%; border: 6px solid #e0b44c; display: grid; place-items: center; background: #131c26; }
  .text { flex: 1; padding: 56px 60px 48px 44px; display: flex; flex-direction: column; border-top: 8px solid #e0b44c; }
  .brand { display: flex; align-items: center; gap: 12px; font-size: 30px; font-weight: 700; }
  .brand svg { width: 38px; height: 38px; color: #6aa5ec; } .brand b { color: #6aa5ec; }
  .eyebrow { margin-top: auto; color: #e0b44c; font-size: 24px; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; }
  h1 { font-size: 66px; line-height: 1.05; margin: 12px 0 18px; }
  h1.long { font-size: 52px; }
  .line { font-size: 28px; color: #c5d2e0; } .stat { margin-top: 10px; font-size: 26px; color: #93a3b5; }
  .live { display: inline-block; margin-top: 18px; font-size: 22px; font-weight: 700; color: #f3a6a6; }
  .url { margin-top: auto; padding-top: 26px; font-size: 24px; color: #93a3b5; }`;

const heroCardHtml = h => `<!doctype html><html><head><meta charset="utf-8"><style>${CARD_CSS}</style></head><body>
  <div class="photo" style="${h.image ? `background-image:url(${dataUri(h.image)});background-position:${h.imageKind === "portrait" ? "50% 30%" : "center"}` : ""}">
    ${h.image ? "" : `<div class="ini">${esc(initials(h.name))}</div>`}</div>
  <div class="text">
    <div class="brand">${PLANE}<span>Air<b>Sky</b>Hero</span></div>
    <div class="eyebrow">${esc(h.role)} · ${esc(h.country)}</div>
    <h1 class="${h.name.length > 24 ? "long" : ""}">${esc(h.name)}</h1>
    <div class="line">${esc(h.flight)} · ${h.year}</div>
    <div class="stat">${h.aboard ? `${h.survived} of ${h.aboard} aboard survived` : esc(h.place)}</div>
    ${h.developing ? '<span class="live">● Developing story</span>' : ""}
    <div class="url">airskyhero.com</div>
  </div></body></html>`;

const homeCardHtml = () => {
  const pics = HEROES.filter(h => h.image && h.imageKind === "portrait").slice(0, 6);
  return `<!doctype html><html><head><meta charset="utf-8"><style>${CARD_CSS}
    .mosaic { width: 500px; height: 630px; flex: none; display: grid; grid-template-columns: 1fr 1fr; position: relative; }
    .mosaic div { background: center 30% / cover no-repeat; }
    .mosaic::after { content: ""; position: absolute; inset: 0; background: linear-gradient(90deg, rgba(11,17,24,.15) 60%, #0b1118); }
    h1 { font-size: 64px; }</style></head><body>
    <div class="mosaic">${pics.map(h => `<div style="background-image:url(${dataUri(h.image)})"></div>`).join("")}</div>
    <div class="text">
      <div class="brand">${PLANE}<span>Air<b>Sky</b>Hero</span></div>
      <div class="eyebrow">${HEROES.length} heroes · ${new Set(HEROES.map(h => h.country)).size} countries</div>
      <h1>Heroes of the sky, around the world</h1>
      <div class="line">Pilots, cabin crew and passengers whose courage saved lives.</div>
      <div class="url">airskyhero.com</div>
    </div></body></html>`;
};

const CHROME = [process.env.CHROME_PATH,
  "C:/Program Files/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
  "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe",
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/usr/bin/google-chrome", "/usr/bin/chromium"].find(p => p && fs.existsSync(p));

if (!CHROME) {
  console.warn("Share images skipped: Chrome not found (set CHROME_PATH to its location).");
} else {
  const { default: puppeteer } = await import("puppeteer-core");
  const browser = await puppeteer.launch({ executablePath: CHROME, headless: true });
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 1200, height: 630, deviceScaleFactor: 1 });
    const shoot = async (file, html) => {
      await page.setContent(html, { waitUntil: "load" });
      await page.evaluate(() => document.fonts.ready);
      return write(file, await page.screenshot({ type: "jpeg", quality: 85 }));
    };
    let n = 0;
    for (const h of ordered) if (await shoot(`share/${heroSlug(h)}.jpg`, heroCardHtml(h))) n++;
    if (await shoot("share/home.jpg", homeCardHtml())) n++;
    for (const f of fs.readdirSync(path.join(ROOT, "share"))) {
      if (f !== "home.jpg" && !slugs.has(f.replace(/\.jpg$/, ""))) fs.rmSync(path.join(ROOT, "share", f));
    }
    console.log(`Share images: ${ordered.length + 1} (${n} updated)`);
  } finally {
    await browser.close();
  }
}
